(("abs" "mixed $number")
("acos" "float $arg")
("acosh" "float $arg")
("addcslashes" "string $str" "string $charlist")
("addslashes" "string $str")
("apache_child_terminate" "")
("apache_get_modules" "")
("apache_get_version" "")
("apache_getenv" "string $variable" "[bool $walk_to_top = '']")
("apache_lookup_uri" "string $filename")
("apache_note" "string $note_name" "[string $note_value = \"\"]")
("apache_request_headers" "")
("apache_reset_timeout" "")
("apache_response_headers" "")
("apache_setenv" "string $variable" "string $value" "[bool $walk_to_top = '']")
("array" "[mixed $... = '']")
("array_change_key_case" "array $array" "[int $case = CASE_LOWER]")
("array_chunk" "array $array" "int $size" "[bool $preserve_keys = '']")
("array_column" "array $input" "mixed $column_key" "[mixed $index_key = '']")
("array_combine" "array $keys" "array $values")
("array_count_values" "array $array")
("array_diff" "array $array1" "array $array2" "[array $... = '']")
("array_diff_assoc" "array $array1" "array $array2" "[array $... = '']")
("array_diff_key" "array $array1" "array $array2" "[array $... = '']")
("array_diff_uassoc" "array $array1" "array $array2" "[array $... = ''" "callable $key_compare_func]")
("array_diff_ukey" "array $array1" "array $array2" "[array $... = ''" "callable $key_compare_func]")
("array_fill" "int $start_index" "int $num" "mixed $value")
("array_fill_keys" "array $keys" "mixed $value")
("array_filter" "array $array" "[callable $callback = ''" "[int $flag = '']]")
("array_flip" "array $array")
("array_intersect" "array $array1" "array $array2" "[array $... = '']")
("array_intersect_assoc" "array $array1" "array $array2" "[array $... = '']")
("array_intersect_key" "array $array1" "array $array2" "[array $... = '']")
("array_intersect_uassoc" "array $array1" "array $array2" "[array $... = ''" "callable $key_compare_func]")
("array_intersect_ukey" "array $array1" "array $array2" "[array $... = ''" "callable $key_compare_func]")
("array_key_exists" "mixed $key" "array $array")
("array_key_first" "array $array")
("array_key_last" "array $array")
("array_keys" "array $array" "mixed $search_value" "[bool $strict = '']")
("array_map" "callable $callback" "array $array1" "[array $... = '']")
("array_merge" "[array $... = '']")
("array_merge_recursive" "[array $... = '']")
("array_multisort" "array $array1" "[mixed $array1_sort_order = SORT_ASC" "[mixed $array1_sort_flags = SORT_REGULAR" "[mixed $... = '']]]")
("array_pad" "array $array" "int $size" "mixed $value")
("array_pop" "array $array")
("array_product" "array $array")
("array_push" "array $array" "[mixed $... = '']")
("array_rand" "array $array" "[int $num = 1]")
("array_reduce" "array $array" "callable $callback" "[mixed $initial = '']")
("array_replace" "array $array1" "[array $... = '']")
("array_replace_recursive" "array $array1" "[array $... = '']")
("array_reverse" "array $array" "[bool $preserve_keys = '']")
("array_search" "mixed $needle" "array $haystack" "[bool $strict = '']")
("array_shift" "array $array")
("array_slice" "array $array" "int $offset" "[int $length = ''" "[bool $preserve_keys = '']]")
("array_splice" "array $input" "int $offset" "[int $length = count($input")
("array_sum" "array $array")
("array_udiff" "array $array1" "array $array2" "[array $... = ''" "callable $value_compare_func]")
("array_udiff_assoc" "array $array1" "array $array2" "[array $... = ''" "callable $value_compare_func]")
("array_udiff_uassoc" "array $array1" "array $array2" "[array $... = ''" "callable $value_compare_func" "callable $key_compare_func]")
("array_uintersect" "array $array1" "array $array2" "[array $... = ''" "callable $value_compare_func]")
("array_uintersect_assoc" "array $array1" "array $array2" "[array $... = ''" "callable $value_compare_func]")
("array_uintersect_uassoc" "array $array1" "array $array2" "[array $... = ''" "callable $value_compare_func" "callable $key_compare_func]")
("array_unique" "array $array" "[int $sort_flags = SORT_STRING]")
("array_unshift" "array $array" "[mixed $... = '']")
("array_values" "array $array")
("array_walk" "array $array" "callable $callback" "[mixed $userdata = '']")
("array_walk_recursive" "array $array" "callable $callback" "[mixed $userdata = '']")
("arsort" "array $array" "[int $sort_flags = SORT_REGULAR]")
("asin" "float $arg")
("asinh" "float $arg")
("asort" "array $array" "[int $sort_flags = SORT_REGULAR]")
("assert" "mixed $assertion" "[string $description = ''" "[Throwable $exception = '']]")
("assert_options" "int $what" "[mixed $value = '']")
("atan" "float $arg")
("atan2" "float $y" "float $x")
("atanh" "float $arg")
("base64_decode" "string $data" "[bool $strict = '']")
("base64_encode" "string $data")
("base_convert" "string $number" "int $frombase" "int $tobase")
("basename" "string $path" "[string $suffix = '']")
("bcadd" "string $left_operand" "string $right_operand" "[int $scale = '']")
("bccomp" "string $left_operand" "string $right_operand" "[int $scale = '']")
("bcdiv" "string $dividend" "string $divisor" "[int $scale = '']")
("bcmod" "string $dividend" "string $divisor" "[int $scale = '']")
("bcmul" "string $left_operand" "string $right_operand" "[int $scale = '']")
("bcpow" "string $base" "string $exponent" "[int $scale = '']")
("bcpowmod" "string $base" "string $exponent" "string $modulus" "[int $scale = '']")
("bcscale" "int $scale")
("bcsqrt" "string $operand" "[int $scale = '']")
("bcsub" "string $left_operand" "string $right_operand" "[int $scale = '']")
("bin2hex" "string $str")
("bind_textdomain_codeset" "string $domain" "string $codeset")
("bindec" "string $binary_string")
("bindtextdomain" "string $domain" "string $directory")
("boolval" "mixed $var")
("bzclose" "resource $bz")
("bzcompress" "string $source" "[int $blocksize = 4" "[int $workfactor = '']]")
("bzdecompress" "string $source" "[int $small = '']")
("bzerrno" "resource $bz")
("bzerror" "resource $bz")
("bzerrstr" "resource $bz")
("bzflush" "resource $bz")
("bzopen" "mixed $file" "string $mode")
("bzread" "resource $bz" "[int $length = 1024]")
("bzwrite" "resource $bz" "string $data" "[int $length = '']")
("cal_days_in_month" "int $calendar" "int $month" "int $year")
("cal_from_jd" "int $jd" "int $calendar")
("cal_info" "[int $calendar = -1]")
("cal_to_jd" "int $calendar" "int $month" "int $day" "int $year")
("call_user_func" "callable $callback" "[mixed $... = '']")
("call_user_func_array" "callable $callback" "array $param_arr")
("call_user_method" "string $method_name" "object $obj" "[mixed $... = '']")
("call_user_method_array" "string $method_name" "object $obj" "array $params")
("ceil" "float $value")
("chdir" "string $directory")
("checkdate" "int $month" "int $day" "int $year")
("checkdnsrr" "string $host" "[string $type = \"MX\"]")
("chgrp" "string $filename" "mixed $group")
("chmod" "string $filename" "int $mode")
("chop" "")
("chown" "string $filename" "mixed $user")
("chr" "int $bytevalue")
("chroot" "string $directory")
("chunk_split" "string $body" "[int $chunklen = 76" "[string $end = \"\r\n\"]]")
("class_alias" "string $original" "string $alias" "[bool $autoload = '']")
("class_exists" "string $class_name" "[bool $autoload = '']")
("class_implements" "mixed $class" "[bool $autoload = '']")
("class_parents" "mixed $class" "[bool $autoload = '']")
("class_uses" "mixed $class" "[bool $autoload = '']")
("clearstatcache" "[bool $clear_realpath_cache = ''" "[string $filename = '']]")
("cli_get_process_title" "")
("cli_set_process_title" "string $title")
("closedir" "[resource $dir_handle = '']")
("closelog" "")
("compact" "mixed $varname1" "[mixed $... = '']")
("connection_aborted" "")
("connection_status" "")
("constant" "string $name")
("convert_cyr_string" "string $str" "string $from" "string $to")
("convert_uudecode" "string $data")
("convert_uuencode" "string $data")
("copy" "string $source" "string $dest" "[resource $context = '']")
("cos" "float $arg")
("cosh" "float $arg")
("count" "mixed $array_or_countable" "[int $mode = COUNT_NORMAL]")
("count_chars" "string $string" "[int $mode = '']")
("crc32" "string $str")
("create_function" "string $args" "string $code")
("crypt" "string $str" "[string $salt = '']")
("ctype_alnum" "string $text")
("ctype_alpha" "string $text")
("ctype_cntrl" "string $text")
("ctype_digit" "string $text")
("ctype_graph" "string $text")
("ctype_lower" "string $text")
("ctype_print" "string $text")
("ctype_punct" "string $text")
("ctype_space" "string $text")
("ctype_upper" "string $text")
("ctype_xdigit" "string $text")
("curl_close" "resource $ch")
("curl_copy_handle" "resource $ch")
("curl_errno" "resource $ch")
("curl_error" "resource $ch")
("curl_escape" "resource $ch" "string $str")
("curl_exec" "resource $ch")
("curl_file_create" "string $filename" "[string $mimetype = ''" "[string $postname = '']]")
("curl_getinfo" "resource $ch" "[int $opt = '']")
("curl_init" "[string $url = '']")
("curl_multi_add_handle" "resource $mh" "resource $ch")
("curl_multi_close" "resource $mh")
("curl_multi_errno" "resource $mh")
("curl_multi_exec" "resource $mh" "int $still_running")
("curl_multi_getcontent" "resource $ch")
("curl_multi_info_read" "resource $mh" "[int $msgs_in_queue = '']")
("curl_multi_init" "")
("curl_multi_remove_handle" "resource $mh" "resource $ch")
("curl_multi_select" "resource $mh" "[float $timeout = 1.0]")
("curl_multi_setopt" "resource $mh" "int $option" "mixed $value")
("curl_multi_strerror" "int $errornum")
("curl_pause" "resource $ch" "int $bitmask")
("curl_reset" "resource $ch")
("curl_setopt" "resource $ch" "int $option" "mixed $value")
("curl_setopt_array" "resource $ch" "array $options")
("curl_share_close" "resource $sh")
("curl_share_errno" "resource $sh")
("curl_share_init" "")
("curl_share_setopt" "resource $sh" "int $option" "string $value")
("curl_share_strerror" "int $errornum")
("curl_strerror" "int $errornum")
("curl_unescape" "resource $ch" "string $str")
("curl_version" "[int $age = CURLVERSION_NOW]")
("current" "array $array")
("date" "string $format" "[int $timestamp = time(")
("date_add" "")
("date_create" "")
("date_create_from_format" "")
("date_create_immutable" "")
("date_create_immutable_from_format" "")
("date_date_set" "")
("date_default_timezone_get" "")
("date_default_timezone_set" "string $timezone_identifier")
("date_diff" "")
("date_format" "")
("date_get_last_errors" "")
("date_interval_create_from_date_string" "")
("date_interval_format" "")
("date_isodate_set" "")
("date_modify" "")
("date_offset_get" "")
("date_parse" "string $date")
("date_parse_from_format" "string $format" "string $date")
("date_sub" "")
("date_sun_info" "int $time" "float $latitude" "float $longitude")
("date_sunrise" "int $timestamp" "[int $format = SUNFUNCS_RET_STRING" "[float $latitude = ini_get(\"date.default_latitude\"")
("date_sunset" "int $timestamp" "[int $format = SUNFUNCS_RET_STRING" "[float $latitude = ini_get(\"date.default_latitude\"")
("date_time_set" "")
("date_timestamp_get" "")
("date_timestamp_set" "")
("date_timezone_get" "")
("date_timezone_set" "")
("dba_close" "resource $handle")
("dba_delete" "string $key" "resource $handle")
("dba_exists" "string $key" "resource $handle")
("dba_fetch" "string $key" "resource $handle" "int $skip")
("dba_firstkey" "resource $handle")
("dba_handlers" "[bool $full_info = '']")
("dba_insert" "string $key" "string $value" "resource $handle")
("dba_key_split" "mixed $key")
("dba_list" "")
("dba_nextkey" "resource $handle")
("dba_open" "string $path" "string $mode" "[string $handler = ''" "[mixed $... = '']]")
("dba_optimize" "resource $handle")
("dba_popen" "string $path" "string $mode" "[string $handler = ''" "[mixed $... = '']]")
("dba_replace" "string $key" "string $value" "resource $handle")
("dba_sync" "resource $handle")
("dcgettext" "string $domain" "string $message" "int $category")
("dcngettext" "string $domain" "string $msgid1" "string $msgid2" "int $n" "int $category")
("debug_backtrace" "[int $options = DEBUG_BACKTRACE_PROVIDE_OBJECT" "[int $limit = '']]")
("debug_print_backtrace" "[int $options = ''" "[int $limit = '']]")
("debug_zval_dump" "mixed $variable" "[mixed $... = '']")
("decbin" "int $number")
("dechex" "int $number")
("decoct" "int $number")
("define" "string $name" "mixed $value" "[bool $case_insensitive = '']")
("defined" "string $name")
("deflate_add" "resource $context" "string $data" "[int $flush_mode = ZLIB_SYNC_FLUSH]")
("deflate_init" "int $encoding" "[array $options = array(")
("deg2rad" "float $number")
("dgettext" "string $domain" "string $message")
("die" "")
("dio_close" "resource $fd")
("dio_fcntl" "resource $fd" "int $cmd" "[mixed $args = '']")
("dio_open" "string $filename" "int $flags" "[int $mode = '']")
("dio_read" "resource $fd" "[int $len = 1024]")
("dio_seek" "resource $fd" "int $pos" "[int $whence = SEEK_SET]")
("dio_stat" "resource $fd")
("dio_tcsetattr" "resource $fd" "array $options")
("dio_truncate" "resource $fd" "int $offset")
("dio_write" "resource $fd" "string $data" "[int $len = '']")
("dir" "string $directory" "[resource $context = '']")
("dirname" "string $path" "[int $levels = 1]")
("disk_free_space" "string $directory")
("disk_total_space" "string $directory")
("diskfreespace" "")
("dl" "string $library")
("dngettext" "string $domain" "string $msgid1" "string $msgid2" "int $n")
("dns_check_record" "")
("dns_get_mx" "")
("dns_get_record" "string $hostname" "[int $type = DNS_ANY" "[array $authns = ''" "[array $addtl = ''" "[bool $raw = '']]]]")
("dom_import_simplexml" "SimpleXMLElement $node")
("doubleval" "")
("each" "array $array")
("easter_date" "[int $year = date(\"Y\"")
("easter_days" "[int $year = date(\"Y\"")
("echo" "string $arg1" "[string $... = '']")
("empty" "mixed $var")
("end" "array $array")
("ereg" "string $pattern" "string $string" "[array $regs = '']")
("ereg_replace" "string $pattern" "string $replacement" "string $string")
("eregi" "string $pattern" "string $string" "[array $regs = '']")
("eregi_replace" "string $pattern" "string $replacement" "string $string")
("error_clear_last" "")
("error_get_last" "")
("error_log" "string $message" "[int $message_type = ''" "[string $destination = ''" "[string $extra_headers = '']]]")
("error_reporting" "[int $level = '']")
("escapeshellarg" "string $arg")
("escapeshellcmd" "string $command")
("eval" "string $code")
("exec" "string $command" "[array $output = ''" "[int $return_var = '']]")
("exif_imagetype" "string $filename")
("exif_read_data" "mixed $stream" "[string $sections = ''" "[bool $arrays = ''" "[bool $thumbnail = '']]]")
("exif_tagname" "int $index")
("exif_thumbnail" "mixed $stream" "[int $width = ''" "[int $height = ''" "[int $imagetype = '']]]")
("exit" "int $status")
("exp" "float $arg")
("explode" "string $delimiter" "string $string" "[int $limit = PHP_INT_MAX]")
("expm1" "float $arg")
("extension_loaded" "string $name")
("extract" "array $array" "[int $flags = EXTR_OVERWRITE" "[string $prefix = '']]")
("ezmlm_hash" "string $addr")
("fastcgi_finish_request" "")
("fclose" "resource $handle")
("feof" "resource $handle")
("fflush" "resource $handle")
("fgetc" "resource $handle")
("fgetcsv" "resource $handle" "[int $length = ''" "[string $delimiter = \"" "\"" "[string $enclosure = '\"'" "[string $escape = \"\\\"]]]]")
("fgets" "resource $handle" "[int $length = '']")
("fgetss" "resource $handle" "[int $length = ''" "[string $allowable_tags = '']]")
("file" "string $filename" "[int $flags = ''" "[resource $context = '']]")
("file_exists" "string $filename")
("file_get_contents" "string $filename" "[bool $use_include_path = ''" "[resource $context = ''" "[int $offset = ''" "[int $maxlen = '']]]]")
("file_put_contents" "string $filename" "mixed $data" "[int $flags = ''" "[resource $context = '']]")
("fileatime" "string $filename")
("filectime" "string $filename")
("filegroup" "string $filename")
("fileinode" "string $filename")
("filemtime" "string $filename")
("fileowner" "string $filename")
("fileperms" "string $filename")
("filesize" "string $filename")
("filetype" "string $filename")
("filter_has_var" "int $type" "string $variable_name")
("filter_id" "string $filtername")
("filter_input" "int $type" "string $variable_name" "[int $filter = FILTER_DEFAULT" "[mixed $options = '']]")
("filter_input_array" "int $type" "[mixed $definition = ''" "[bool $add_empty = '']]")
("filter_list" "")
("filter_var" "mixed $variable" "[int $filter = FILTER_DEFAULT" "[mixed $options = '']]")
("filter_var_array" "array $data" "[mixed $definition = ''" "[bool $add_empty = '']]")
("floatval" "mixed $var")
("flock" "resource $handle" "int $operation" "[int $wouldblock = '']")
("floor" "float $value")
("flush" "")
("fmod" "float $x" "float $y")
("fnmatch" "string $pattern" "string $string" "[int $flags = '']")
("fopen" "string $filename" "string $mode" "[bool $use_include_path = ''" "[resource $context = '']]")
("forward_static_call" "callable $function" "[mixed $... = '']")
("forward_static_call_array" "callable $function" "array $parameters")
("fpassthru" "resource $handle")
("fprintf" "resource $handle" "string $format" "[mixed $... = '']")
("fputcsv" "resource $handle" "array $fields" "[string $delimiter = \"" "\"" "[string $enclosure = '\"'" "[string $escape_char = \"\\\"]]]")
("fputs" "")
("fread" "resource $handle" "int $length")
("frenchtojd" "int $month" "int $day" "int $year")
("fscanf" "resource $handle" "string $format" "[mixed $... = '']")
("fseek" "resource $handle" "int $offset" "[int $whence = SEEK_SET]")
("fsockopen" "string $hostname" "[int $port = -1" "[int $errno = ''" "[string $errstr = ''" "[float $timeout = ini_get(\"default_socket_timeout\"")
("fstat" "resource $handle")
("ftell" "resource $handle")
("ftok" "string $pathname" "string $proj")
("ftp_alloc" "resource $ftp_stream" "int $filesize" "[string $result = '']")
("ftp_append" "resource $ftp" "string $remote_file" "string $local_file" "[int $mode = '']")
("ftp_cdup" "resource $ftp_stream")
("ftp_chdir" "resource $ftp_stream" "string $directory")
("ftp_chmod" "resource $ftp_stream" "int $mode" "string $filename")
("ftp_close" "resource $ftp_stream")
("ftp_connect" "string $host" "[int $port = 21" "[int $timeout = 90]]")
("ftp_delete" "resource $ftp_stream" "string $path")
("ftp_exec" "resource $ftp_stream" "string $command")
("ftp_fget" "resource $ftp_stream" "resource $handle" "string $remote_file" "[int $mode = ''" "[int $resumepos = '']]")
("ftp_fput" "resource $ftp_stream" "string $remote_file" "resource $handle" "[int $mode = ''" "[int $startpos = '']]")
("ftp_get" "resource $ftp_stream" "string $local_file" "string $remote_file" "[int $mode = ''" "[int $resumepos = '']]")
("ftp_get_option" "resource $ftp_stream" "int $option")
("ftp_login" "resource $ftp_stream" "string $username" "string $password")
("ftp_mdtm" "resource $ftp_stream" "string $remote_file")
("ftp_mkdir" "resource $ftp_stream" "string $directory")
("ftp_mlsd" "resource $ftp_stream" "string $directory")
("ftp_nb_continue" "resource $ftp_stream")
("ftp_nb_fget" "resource $ftp_stream" "resource $handle" "string $remote_file" "[int $mode = ''" "[int $resumepos = '']]")
("ftp_nb_fput" "resource $ftp_stream" "string $remote_file" "resource $handle" "[int $mode = ''" "[int $startpos = '']]")
("ftp_nb_get" "resource $ftp_stream" "string $local_file" "string $remote_file" "[int $mode = ''" "[int $resumepos = '']]")
("ftp_nb_put" "resource $ftp_stream" "string $remote_file" "string $local_file" "[int $mode = ''" "[int $startpos = '']]")
("ftp_nlist" "resource $ftp_stream" "string $directory")
("ftp_pasv" "resource $ftp_stream" "bool $pasv")
("ftp_put" "resource $ftp_stream" "string $remote_file" "string $local_file" "[int $mode = ''" "[int $startpos = '']]")
("ftp_pwd" "resource $ftp_stream")
("ftp_quit" "")
("ftp_raw" "resource $ftp_stream" "string $command")
("ftp_rawlist" "resource $ftp_stream" "string $directory" "[bool $recursive = '']")
("ftp_rename" "resource $ftp_stream" "string $oldname" "string $newname")
("ftp_rmdir" "resource $ftp_stream" "string $directory")
("ftp_set_option" "resource $ftp_stream" "int $option" "mixed $value")
("ftp_site" "resource $ftp_stream" "string $command")
("ftp_size" "resource $ftp_stream" "string $remote_file")
("ftp_ssl_connect" "string $host" "[int $port = 21" "[int $timeout = 90]]")
("ftp_systype" "resource $ftp_stream")
("ftruncate" "resource $handle" "int $size")
("func_get_arg" "int $arg_num")
("func_get_args" "")
("func_num_args" "")
("function_exists" "string $function_name")
("fwrite" "resource $handle" "string $string" "[int $length = '']")
("gc_collect_cycles" "")
("gc_disable" "")
("gc_enable" "")
("gc_enabled" "")
("gc_mem_caches" "")
("gc_status" "")
("gd_info" "")
("get_browser" "[string $user_agent = ''" "[bool $return_array = '']]")
("get_called_class" "")
("get_cfg_var" "string $option")
("get_class" "[object $object = '']")
("get_class_methods" "mixed $class_name")
("get_class_vars" "string $class_name")
("get_current_user" "")
("get_declared_classes" "")
("get_declared_interfaces" "")
("get_declared_traits" "")
("get_defined_constants" "[bool $categorize = '']")
("get_defined_functions" "[bool $exclude_disabled = '']")
("get_defined_vars" "")
("get_extension_funcs" "string $module_name")
("get_headers" "string $url" "[int $format = ''" "[resource $context = '']]")
("get_html_translation_table" "[int $table = HTML_SPECIALCHARS" "[int $flags = ENT_COMPAT | ENT_HTML401" "[string $encoding = \"UTF-8\"]]]")
("get_include_path" "")
("get_included_files" "")
("get_loaded_extensions" "[bool $zend_extensions = '']")
("get_magic_quotes_gpc" "")
("get_magic_quotes_runtime" "")
("get_meta_tags" "string $filename" "[bool $use_include_path = '']")
("get_object_vars" "object $object")
("get_parent_class" "[mixed $object = '']")
("get_required_files" "")
("get_resource_type" "resource $handle")
("get_resources" "[string $type = '']")
("getallheaders" "")
("getcwd" "")
("getdate" "[int $timestamp = time(")
("getenv" "string $varname" "[bool $local_only = '']")
("gethostbyaddr" "string $ip_address")
("gethostbyname" "string $hostname")
("gethostbynamel" "string $hostname")
("gethostname" "")
("getimagesize" "string $filename" "[array $imageinfo = '']")
("getimagesizefromstring" "string $imagedata" "[array $imageinfo = '']")
("getlastmod" "")
("getmxrr" "string $hostname" "array $mxhosts" "[array $weight = '']")
("getmygid" "")
("getmyinode" "")
("getmypid" "")
("getmyuid" "")
("getopt" "string $options" "[array $longopts = ''" "[int $optind = '']]")
("getprotobyname" "string $name")
("getprotobynumber" "int $number")
("getrandmax" "")
("getrusage" "[int $who = '']")
("getservbyname" "string $service" "string $protocol")
("getservbyport" "int $port" "string $protocol")
("gettext" "string $message")
("gettimeofday" "[bool $return_float = '']")
("gettype" "mixed $var")
("glob" "string $pattern" "[int $flags = '']")
("gmdate" "string $format" "[int $timestamp = time(")
("gmmktime" "[int $hour = gmdate(\"H\"")
("gmp_abs" "GMP $a")
("gmp_add" "GMP $a" "GMP $b")
("gmp_and" "GMP $a" "GMP $b")
("gmp_binomial" "mixed $n" "int $k")
("gmp_clrbit" "GMP $a" "int $index")
("gmp_cmp" "GMP $a" "GMP $b")
("gmp_com" "GMP $a")
("gmp_div" "")
("gmp_div_q" "GMP $a" "GMP $b" "[int $round = GMP_ROUND_ZERO]")
("gmp_div_qr" "GMP $n" "GMP $d" "[int $round = GMP_ROUND_ZERO]")
("gmp_div_r" "GMP $n" "GMP $d" "[int $round = GMP_ROUND_ZERO]")
("gmp_divexact" "GMP $n" "GMP $d")
("gmp_export" "GMP $gmpnumber" "[int $word_size = 1" "[int $options =  | ]]")
("gmp_fact" "mixed $a")
("gmp_gcd" "GMP $a" "GMP $b")
("gmp_gcdext" "GMP $a" "GMP $b")
("gmp_hamdist" "GMP $a" "GMP $b")
("gmp_import" "string $data" "[int $word_size = 1" "[int $options =  | ]]")
("gmp_init" "mixed $number" "[int $base = '']")
("gmp_intval" "GMP $gmpnumber")
("gmp_invert" "GMP $a" "GMP $b")
("gmp_jacobi" "GMP $a" "GMP $p")
("gmp_kronecker" "mixed $a" "mixed $b")
("gmp_lcm" "mixed $a" "mixed $b")
("gmp_legendre" "GMP $a" "GMP $p")
("gmp_mod" "GMP $n" "GMP $d")
("gmp_mul" "GMP $a" "GMP $b")
("gmp_neg" "GMP $a")
("gmp_nextprime" "int $a")
("gmp_or" "GMP $a" "GMP $b")
("gmp_perfect_power" "mixed $a")
("gmp_perfect_square" "GMP $a")
("gmp_popcount" "GMP $a")
("gmp_pow" "GMP $base" "int $exp")
("gmp_powm" "GMP $base" "GMP $exp" "GMP $mod")
("gmp_prob_prime" "GMP $a" "[int $reps = 10]")
("gmp_random" "[int $limiter = 20]")
("gmp_random_bits" "int $bits")
("gmp_random_range" "GMP $min" "GMP $max")
("gmp_random_seed" "mixed $seed")
("gmp_root" "GMP $a" "int $nth")
("gmp_rootrem" "GMP $a" "int $nth")
("gmp_scan0" "GMP $a" "int $start")
("gmp_scan1" "GMP $a" "int $start")
("gmp_setbit" "GMP $a" "int $index" "[bool $bit_on = '']")
("gmp_sign" "GMP $a")
("gmp_sqrt" "GMP $a")
("gmp_sqrtrem" "GMP $a")
("gmp_strval" "GMP $gmpnumber" "[int $base = 10]")
("gmp_sub" "GMP $a" "GMP $b")
("gmp_testbit" "GMP $a" "int $index")
("gmp_xor" "GMP $a" "GMP $b")
("gmstrftime" "string $format" "[int $timestamp = time(")
("gregoriantojd" "int $month" "int $day" "int $year")
("gzclose" "resource $zp")
("gzcompress" "string $data" "[int $level = -1" "[int $encoding = ZLIB_ENCODING_DEFLATE]]")
("gzdecode" "string $data" "[int $length = '']")
("gzdeflate" "string $data" "[int $level = -1" "[int $encoding = ZLIB_ENCODING_RAW]]")
("gzencode" "string $data" "[int $level = -1" "[int $encoding_mode = FORCE_GZIP]]")
("gzeof" "resource $zp")
("gzfile" "string $filename" "[int $use_include_path = '']")
("gzgetc" "resource $zp")
("gzgets" "resource $zp" "[int $length = '']")
("gzgetss" "resource $zp" "int $length" "[string $allowable_tags = '']")
("gzinflate" "string $data" "[int $length = '']")
("gzopen" "string $filename" "string $mode" "[int $use_include_path = '']")
("gzpassthru" "resource $zp")
("gzputs" "")
("gzread" "resource $zp" "int $length")
("gzrewind" "resource $zp")
("gzseek" "resource $zp" "int $offset" "[int $whence = SEEK_SET]")
("gztell" "resource $zp")
("gzuncompress" "string $data" "[int $length = '']")
("gzwrite" "resource $zp" "string $string" "[int $length = '']")
("hash_copy" "HashContext $context")
("hash_equals" "string $known_string" "string $user_string")
("hash_hkdf" "string $algo" "string $ikm" "[int $length = ''" "[string $info = ''" "[string $salt = '']]]")
("hash_hmac_algos" "")
("hash_pbkdf2" "string $algo" "string $password" "string $salt" "int $iterations" "[int $length = ''" "[bool $raw_output = '']]")
("header" "string $header" "[bool $replace = ''" "[int $http_response_code = '']]")
("header_register_callback" "callable $callback")
("header_remove" "[string $name = '']")
("headers_list" "")
("headers_sent" "[string $file = ''" "[int $line = '']]")
("hebrev" "string $hebrew_text" "[int $max_chars_per_line = '']")
("hebrevc" "string $hebrew_text" "[int $max_chars_per_line = '']")
("hex2bin" "string $data")
("hexdec" "string $hex_string")
("highlight_file" "string $filename" "[bool $return = '']")
("highlight_string" "string $str" "[bool $return = '']")
("hrtime" "[bool $get_as_number = '']")
("html_entity_decode" "string $string" "[int $flags = ENT_COMPAT | ENT_HTML401" "[string $encoding = ini_get(\"default_charset\"")
("htmlentities" "string $string" "[int $flags = ENT_COMPAT | ENT_HTML401" "[string $encoding = ini_get(\"default_charset\"")
("htmlspecialchars" "string $string" "[int $flags = ENT_COMPAT | ENT_HTML401" "[string $encoding = ini_get(\"default_charset\"")
("htmlspecialchars_decode" "string $string" "[int $flags = ENT_COMPAT | ENT_HTML401]")
("http_build_query" "mixed $query_data" "[string $numeric_prefix = ''" "[string $arg_separator = ''" "[int $enc_type = '']]]")
("http_response_code" "[int $response_code = '']")
("hypot" "float $x" "float $y")
("iconv" "string $in_charset" "string $out_charset" "string $str")
("iconv_get_encoding" "[string $type = \"all\"]")
("iconv_mime_decode" "string $encoded_header" "[int $mode = ''" "[string $charset = ini_get(\"iconv.internal_encoding\"")
("iconv_mime_decode_headers" "string $encoded_headers" "[int $mode = ''" "[string $charset = ini_get(\"iconv.internal_encoding\"")
("iconv_mime_encode" "string $field_name" "string $field_value" "[array $preferences = '']")
("iconv_set_encoding" "string $type" "string $charset")
("iconv_strlen" "string $str" "[string $charset = ini_get(\"iconv.internal_encoding\"")
("iconv_strpos" "string $haystack" "string $needle" "[int $offset = ''" "[string $charset = ini_get(\"iconv.internal_encoding\"")
("iconv_strrpos" "string $haystack" "string $needle" "[string $charset = ini_get(\"iconv.internal_encoding\"")
("iconv_substr" "string $str" "int $offset" "[int $length = iconv_strlen($str" "$charset")
("idate" "string $format" "[int $timestamp = time(")
("ignore_user_abort" "[bool $value = '']")
("image2wbmp" "resource $image" "[string $filename = ''" "[int $foreground = '']]")
("image_type_to_extension" "int $imagetype" "[bool $include_dot = '']")
("image_type_to_mime_type" "int $imagetype")
("imageaffine" "resource $image" "array $affine" "[array $clip = '']")
("imageaffinematrixconcat" "array $m1" "array $m2")
("imageaffinematrixget" "int $type" "[mixed $options = '']")
("imagealphablending" "resource $image" "bool $blendmode")
("imageantialias" "resource $image" "bool $enabled")
("imagearc" "resource $image" "int $cx" "int $cy" "int $width" "int $height" "int $start" "int $end" "int $color")
("imagebmp" "resource $image" "[mixed $to = ''" "[bool $compressed = '']]")
("imagechar" "resource $image" "int $font" "int $x" "int $y" "string $c" "int $color")
("imagecharup" "resource $image" "int $font" "int $x" "int $y" "string $c" "int $color")
("imagecolorallocate" "resource $image" "int $red" "int $green" "int $blue")
("imagecolorallocatealpha" "resource $image" "int $red" "int $green" "int $blue" "int $alpha")
("imagecolorat" "resource $image" "int $x" "int $y")
("imagecolorclosest" "resource $image" "int $red" "int $green" "int $blue")
("imagecolorclosestalpha" "resource $image" "int $red" "int $green" "int $blue" "int $alpha")
("imagecolorclosesthwb" "resource $image" "int $red" "int $green" "int $blue")
("imagecolordeallocate" "resource $image" "int $color")
("imagecolorexact" "resource $image" "int $red" "int $green" "int $blue")
("imagecolorexactalpha" "resource $image" "int $red" "int $green" "int $blue" "int $alpha")
("imagecolormatch" "resource $image1" "resource $image2")
("imagecolorresolve" "resource $image" "int $red" "int $green" "int $blue")
("imagecolorresolvealpha" "resource $image" "int $red" "int $green" "int $blue" "int $alpha")
("imagecolorset" "resource $image" "int $index" "int $red" "int $green" "int $blue" "[int $alpha = '']")
("imagecolorsforindex" "resource $image" "int $index")
("imagecolorstotal" "resource $image")
("imagecolortransparent" "resource $image" "int $color")
("imageconvolution" "resource $image" "array $matrix" "float $div" "float $offset")
("imagecopy" "resource $dst_im" "resource $src_im" "int $dst_x" "int $dst_y" "int $src_x" "int $src_y" "int $src_w" "int $src_h")
("imagecopymerge" "resource $dst_im" "resource $src_im" "int $dst_x" "int $dst_y" "int $src_x" "int $src_y" "int $src_w" "int $src_h" "int $pct")
("imagecopymergegray" "resource $dst_im" "resource $src_im" "int $dst_x" "int $dst_y" "int $src_x" "int $src_y" "int $src_w" "int $src_h" "int $pct")
("imagecopyresampled" "resource $dst_image" "resource $src_image" "int $dst_x" "int $dst_y" "int $src_x" "int $src_y" "int $dst_w" "int $dst_h" "int $src_w" "int $src_h")
("imagecopyresized" "resource $dst_image" "resource $src_image" "int $dst_x" "int $dst_y" "int $src_x" "int $src_y" "int $dst_w" "int $dst_h" "int $src_w" "int $src_h")
("imagecreate" "int $width" "int $height")
("imagecreatefrombmp" "string $filename")
("imagecreatefromgd" "string $filename")
("imagecreatefromgd2" "string $filename")
("imagecreatefromgd2part" "string $filename" "int $srcX" "int $srcY" "int $width" "int $height")
("imagecreatefromgif" "string $filename")
("imagecreatefromjpeg" "string $filename")
("imagecreatefrompng" "string $filename")
("imagecreatefromstring" "string $image")
("imagecreatefromwbmp" "string $filename")
("imagecreatefromwebp" "string $filename")
("imagecreatefromxbm" "string $filename")
("imagecreatefromxpm" "string $filename")
("imagecreatetruecolor" "int $width" "int $height")
("imagecrop" "resource $image" "array $rect")
("imagecropauto" "resource $image" "[int $mode = ''" "[float $threshold = .5" "[int $color = -1]]]")
("imagedashedline" "resource $image" "int $x1" "int $y1" "int $x2" "int $y2" "int $color")
("imagedestroy" "resource $image")
("imageellipse" "resource $image" "int $cx" "int $cy" "int $width" "int $height" "int $color")
("imagefill" "resource $image" "int $x" "int $y" "int $color")
("imagefilledarc" "resource $image" "int $cx" "int $cy" "int $width" "int $height" "int $start" "int $end" "int $color" "int $style")
("imagefilledellipse" "resource $image" "int $cx" "int $cy" "int $width" "int $height" "int $color")
("imagefilledpolygon" "resource $image" "array $points" "int $num_points" "int $color")
("imagefilledrectangle" "resource $image" "int $x1" "int $y1" "int $x2" "int $y2" "int $color")
("imagefilltoborder" "resource $image" "int $x" "int $y" "int $border" "int $color")
("imagefilter" "resource $image" "int $filtertype" "[int $arg1 = ''" "[int $arg2 = ''" "[int $arg3 = ''" "[int $arg4 = '']]]]")
("imageflip" "resource $image" "int $mode")
("imagefontheight" "int $font")
("imagefontwidth" "int $font")
("imageftbbox" "float $size" "float $angle" "string $fontfile" "string $text" "[array $extrainfo = '']")
("imagefttext" "resource $image" "float $size" "float $angle" "int $x" "int $y" "int $color" "string $fontfile" "string $text" "[array $extrainfo = '']")
("imagegammacorrect" "resource $image" "float $inputgamma" "float $outputgamma")
("imagegd" "resource $image" "[mixed $to = null]")
("imagegd2" "resource $image" "[mixed $to = null" "[int $chunk_size = 128" "[int $type = IMG_GD2_RAW]]]")
("imagegetclip" "resource $im")
("imagegif" "resource $image" "[mixed $to = '']")
("imagegrabscreen" "")
("imagegrabwindow" "int $window_handle" "[int $client_area = '']")
("imageinterlace" "resource $image" "[int $interlace = '']")
("imageistruecolor" "resource $image")
("imagejpeg" "resource $image" "[mixed $to = ''" "[int $quality = -1]]")
("imagelayereffect" "resource $image" "int $effect")
("imageline" "resource $image" "int $x1" "int $y1" "int $x2" "int $y2" "int $color")
("imageloadfont" "string $file")
("imageopenpolygon" "resource $image" "array $points" "int $num_points" "int $color")
("imagepalettecopy" "resource $destination" "resource $source")
("imagepalettetotruecolor" "resource $src")
("imagepng" "resource $image" "[mixed $to = ''" "[int $quality = -1" "[int $filters = -1]]]")
("imagepolygon" "resource $image" "array $points" "int $num_points" "int $color")
("imagepsbbox" "string $text" "resource $font" "int $size" "int $space" "int $tightness" "float $angle")
("imagepsencodefont" "resource $font_index" "string $encodingfile")
("imagepsextendfont" "resource $font_index" "float $extend")
("imagepsfreefont" "resource $font_index")
("imagepsloadfont" "string $filename")
("imagepsslantfont" "resource $font_index" "float $slant")
("imagepstext" "resource $image" "string $text" "resource $font_index" "int $size" "int $foreground" "int $background" "int $x" "int $y" "[int $space = ''" "[int $tightness = ''" "[float $angle = 0.0" "[int $antialias_steps = 4]]]]")
("imagerectangle" "resource $image" "int $x1" "int $y1" "int $x2" "int $y2" "int $color")
("imageresolution" "resource $image" "int $res_x" "[int $res_y = $res_x]")
("imagerotate" "resource $image" "float $angle" "int $bgd_color" "[int $ignore_transparent = '']")
("imagesavealpha" "resource $image" "bool $saveflag")
("imagescale" "resource $image" "int $new_width" "[int $new_height = -1" "[int $mode = IMG_BILINEAR_FIXED]]")
("imagesetbrush" "resource $image" "resource $brush")
("imagesetclip" "resource $im" "int $x1" "int $y1" "int $x2" "int $y2")
("imagesetinterpolation" "resource $image" "[int $method = IMG_BILINEAR_FIXED]")
("imagesetpixel" "resource $image" "int $x" "int $y" "int $color")
("imagesetstyle" "resource $image" "array $style")
("imagesetthickness" "resource $image" "int $thickness")
("imagesettile" "resource $image" "resource $tile")
("imagestring" "resource $image" "int $font" "int $x" "int $y" "string $string" "int $color")
("imagestringup" "resource $image" "int $font" "int $x" "int $y" "string $string" "int $color")
("imagesx" "resource $image")
("imagesy" "resource $image")
("imagetruecolortopalette" "resource $image" "bool $dither" "int $ncolors")
("imagettfbbox" "float $size" "float $angle" "string $fontfile" "string $text")
("imagettftext" "resource $image" "float $size" "float $angle" "int $x" "int $y" "int $color" "string $fontfile" "string $text")
("imagetypes" "")
("imagewbmp" "resource $image" "[mixed $to = ''" "[int $foreground = '']]")
("imagewebp" "resource $image" "[mixed $to = ''" "[int $quality = 80]]")
("imagexbm" "resource $image" "[string $filename = ''" "[int $foreground = '']]")
("implode" "string $glue" "array $pieces")
("import_request_variables" "string $types" "[string $prefix = '']")
("in_array" "mixed $needle" "array $haystack" "[bool $strict = '']")
("inet_ntop" "string $in_addr")
("inet_pton" "string $address")
("inflate_add" "resource $context" "string $encoded_data" "[int $flush_mode = ZLIB_SYNC_FLUSH]")
("inflate_get_read_len" "resource $resource")
("inflate_get_status" "resource $resource")
("inflate_init" "int $encoding" "[array $options = array(")
("ini_alter" "")
("ini_get" "string $varname")
("ini_get_all" "[string $extension = ''" "[bool $details = '']]")
("ini_restore" "string $varname")
("ini_set" "string $varname" "string $newvalue")
("intdiv" "int $dividend" "int $divisor")
("interface_exists" "string $interface_name" "[bool $autoload = '']")
("intl_error_name" "int $error_code")
("intl_get_error_code" "")
("intl_get_error_message" "")
("intl_is_failure" "int $error_code")
("intlcal_get_error_code" "IntlCalendar $calendar")
("intlcal_get_error_message" "IntlCalendar $calendar")
("intltz_get_error_code" "")
("intltz_get_error_message" "")
("intval" "mixed $var" "[int $base = 10]")
("ip2long" "string $ip_address")
("iptcembed" "string $iptcdata" "string $jpeg_file_name" "[int $spool = '']")
("iptcparse" "string $iptcblock")
("is_a" "mixed $object" "string $class_name" "[bool $allow_string = '']")
("is_array" "mixed $var")
("is_bool" "mixed $var")
("is_callable" "mixed $var" "[bool $syntax_only = ''" "[string $callable_name = '']]")
("is_countable" "mixed $var")
("is_dir" "string $filename")
("is_double" "")
("is_executable" "string $filename")
("is_file" "string $filename")
("is_finite" "float $val")
("is_float" "mixed $var")
("is_infinite" "float $val")
("is_int" "mixed $var")
("is_integer" "")
("is_iterable" "mixed $var")
("is_link" "string $filename")
("is_long" "")
("is_nan" "float $val")
("is_null" "mixed $var")
("is_numeric" "mixed $var")
("is_object" "mixed $var")
("is_readable" "string $filename")
("is_real" "")
("is_resource" "mixed $var")
("is_scalar" "mixed $var")
("is_string" "mixed $var")
("is_subclass_of" "mixed $object" "string $class_name" "[bool $allow_string = '']")
("is_uploaded_file" "string $filename")
("is_writable" "string $filename")
("is_writeable" "")
("isset" "mixed $var" "[mixed $... = '']")
("iterator_apply" "Traversable $iterator" "callable $function" "[array $args = '']")
("iterator_count" "Traversable $iterator")
("iterator_to_array" "Traversable $iterator" "[bool $use_keys = '']")
("jddayofweek" "int $julianday" "[int $mode = CAL_DOW_DAYNO]")
("jdmonthname" "int $julianday" "int $mode")
("jdtofrench" "int $juliandaycount")
("jdtogregorian" "int $julianday")
("jdtojewish" "int $juliandaycount" "[bool $hebrew = ''" "[int $fl = '']]")
("jdtojulian" "int $julianday")
("jdtounix" "int $jday")
("jewishtojd" "int $month" "int $day" "int $year")
("join" "")
("jpeg2wbmp" "string $jpegname" "string $wbmpname" "int $dest_height" "int $dest_width" "int $threshold")
("json_decode" "string $json" "[bool $assoc = ''" "[int $depth = 512" "[int $options = '']]]")
("json_encode" "mixed $value" "[int $options = ''" "[int $depth = 512]]")
("json_last_error" "")
("json_last_error_msg" "")
("juliantojd" "int $month" "int $day" "int $year")
("key" "array $array")
("key_exists" "")
("krsort" "array $array" "[int $sort_flags = SORT_REGULAR]")
("ksort" "array $array" "[int $sort_flags = SORT_REGULAR]")
("lcfirst" "string $str")
("lcg_value" "")
("lchgrp" "string $filename" "mixed $group")
("lchown" "string $filename" "mixed $user")
("levenshtein" "string $str1" "string $str2" "int $cost_ins" "int $cost_rep" "int $cost_del")
("libxml_clear_errors" "")
("libxml_disable_entity_loader" "[bool $disable = '']")
("libxml_get_errors" "")
("libxml_get_last_error" "")
("libxml_set_external_entity_loader" "callable $resolver_function")
("libxml_set_streams_context" "resource $streams_context")
("libxml_use_internal_errors" "[bool $use_errors = '']")
("link" "string $target" "string $link")
("linkinfo" "string $path")
("list" "mixed $var1" "[mixed $... = '']")
("localeconv" "")
("localtime" "[int $timestamp = time(")
("log" "float $arg" "[float $base = M_E]")
("log10" "float $arg")
("log1p" "float $number")
("long2ip" "int $proper_address")
("lstat" "string $filename")
("ltrim" "string $str" "[string $character_mask = '']")
("mail" "string $to" "string $subject" "string $message" "[mixed $additional_headers = ''" "[string $additional_parameters = '']]")
("max" "array $values" "mixed $value1" "[mixed $... = '']")
("mb_check_encoding" "[string $var = ''" "[string $encoding = mb_internal_encoding(")
("mb_chr" "int $cp" "[string $encoding = '']")
("mb_convert_case" "string $str" "int $mode" "[string $encoding = mb_internal_encoding(")
("mb_convert_encoding" "string $str" "string $to_encoding" "[mixed $from_encoding = mb_internal_encoding(")
("mb_convert_kana" "string $str" "[string $option = \"KV\"" "[string $encoding = mb_internal_encoding(")
("mb_convert_variables" "string $to_encoding" "mixed $from_encoding" "mixed $vars" "[mixed $... = '']")
("mb_decode_mimeheader" "string $str")
("mb_decode_numericentity" "string $str" "array $convmap" "[string $encoding = mb_internal_encoding(")
("mb_detect_encoding" "string $str" "[mixed $encoding_list = mb_detect_order(")
("mb_detect_order" "[mixed $encoding_list = mb_detect_order(")
("mb_encode_mimeheader" "string $str" "[string $charset = determined by mb_language(")
("mb_encode_numericentity" "string $str" "array $convmap" "[string $encoding = mb_internal_encoding(")
("mb_encoding_aliases" "string $encoding")
("mb_ereg" "string $pattern" "string $string" "[array $regs = '']")
("mb_ereg_match" "string $pattern" "string $string" "[string $option = \"msr\"]")
("mb_ereg_replace" "string $pattern" "string $replacement" "string $string" "[string $option = \"msr\"]")
("mb_ereg_replace_callback" "string $pattern" "callable $callback" "string $string" "[string $option = \"msr\"]")
("mb_ereg_search" "[string $pattern = ''" "[string $option = \"ms\"]]")
("mb_ereg_search_getpos" "")
("mb_ereg_search_getregs" "")
("mb_ereg_search_init" "string $string" "[string $pattern = ''" "[string $option = \"msr\"]]")
("mb_ereg_search_pos" "[string $pattern = ''" "[string $option = \"ms\"]]")
("mb_ereg_search_regs" "[string $pattern = ''" "[string $option = \"ms\"]]")
("mb_ereg_search_setpos" "int $position")
("mb_eregi" "string $pattern" "string $string" "[array $regs = '']")
("mb_eregi_replace" "string $pattern" "string $replace" "string $string" "[string $option = \"msri\"]")
("mb_get_info" "[string $type = \"all\"]")
("mb_http_input" "[string $type = \"\"]")
("mb_http_output" "[string $encoding = mb_http_output(")
("mb_internal_encoding" "[string $encoding = mb_internal_encoding(")
("mb_language" "[string $language = mb_language(")
("mb_list_encodings" "")
("mb_ord" "string $str" "[string $encoding = '']")
("mb_output_handler" "string $contents" "int $status")
("mb_parse_str" "string $encoded_string" "[array $result = '']")
("mb_preferred_mime_name" "string $encoding")
("mb_regex_encoding" "[string $encoding = mb_regex_encoding(")
("mb_regex_set_options" "[string $options = mb_regex_set_options(")
("mb_scrub" "string $str" "[string $encoding = '']")
("mb_send_mail" "string $to" "string $subject" "string $message" "[mixed $additional_headers = ''" "[string $additional_parameter = '']]")
("mb_split" "string $pattern" "string $string" "[int $limit = -1]")
("mb_strcut" "string $str" "int $start" "[int $length = null" "[string $encoding = mb_internal_encoding(")
("mb_strimwidth" "string $str" "int $start" "int $width" "[string $trimmarker = \"\"" "[string $encoding = mb_internal_encoding(")
("mb_stripos" "string $haystack" "string $needle" "[int $offset = ''" "[string $encoding = mb_internal_encoding(")
("mb_stristr" "string $haystack" "string $needle" "[bool $before_needle = ''" "[string $encoding = mb_internal_encoding(")
("mb_strlen" "string $str" "[string $encoding = mb_internal_encoding(")
("mb_strpos" "string $haystack" "string $needle" "[int $offset = ''" "[string $encoding = mb_internal_encoding(")
("mb_strrchr" "string $haystack" "string $needle" "[bool $part = ''" "[string $encoding = mb_internal_encoding(")
("mb_strrichr" "string $haystack" "string $needle" "[bool $part = ''" "[string $encoding = mb_internal_encoding(")
("mb_strripos" "string $haystack" "string $needle" "[int $offset = ''" "[string $encoding = mb_internal_encoding(")
("mb_strrpos" "string $haystack" "string $needle" "[int $offset = ''" "[string $encoding = mb_internal_encoding(")
("mb_strstr" "string $haystack" "string $needle" "[bool $before_needle = ''" "[string $encoding = mb_internal_encoding(")
("mb_strtolower" "string $str" "[string $encoding = mb_internal_encoding(")
("mb_strtoupper" "string $str" "[string $encoding = mb_internal_encoding(")
("mb_strwidth" "string $str" "[string $encoding = mb_internal_encoding(")
("mb_substitute_character" "[mixed $substchar = mb_substitute_character(")
("mb_substr" "string $str" "int $start" "[int $length = null" "[string $encoding = mb_internal_encoding(")
("mb_substr_count" "string $haystack" "string $needle" "[string $encoding = mb_internal_encoding(")
("md5" "string $str" "[bool $raw_output = '']")
("md5_file" "string $filename" "[bool $raw_output = '']")
("memory_get_peak_usage" "[bool $real_usage = '']")
("memory_get_usage" "[bool $real_usage = '']")
("metaphone" "string $str" "[int $phonemes = '']")
("method_exists" "mixed $object" "string $method_name")
("mhash" "int $hash" "string $data" "[string $key = '']")
("mhash_count" "")
("mhash_get_block_size" "int $hash")
("mhash_get_hash_name" "int $hash")
("mhash_keygen_s2k" "int $hash" "string $password" "string $salt" "int $bytes")
("microtime" "[bool $get_as_float = '']")
("mime_content_type" "string $filename")
("min" "array $values" "mixed $value1" "[mixed $... = '']")
("mkdir" "string $pathname" "[int $mode = 0777" "[bool $recursive = ''" "[resource $context = '']]]")
("mktime" "[int $hour = date(\"H\"")
("money_format" "string $format" "float $number")
("move_uploaded_file" "string $filename" "string $destination")
("msession_connect" "string $host" "string $port")
("msession_count" "")
("msession_create" "string $session" "[string $classname = ''" "[string $data = '']]")
("msession_destroy" "string $name")
("msession_disconnect" "")
("msession_find" "string $name" "string $value")
("msession_get" "string $session" "string $name" "string $value")
("msession_get_array" "string $session")
("msession_get_data" "string $session")
("msession_inc" "string $session" "string $name")
("msession_list" "")
("msession_listvar" "string $name")
("msession_lock" "string $name")
("msession_plugin" "string $session" "string $val" "[string $param = '']")
("msession_randstr" "int $param")
("msession_set" "string $session" "string $name" "string $value")
("msession_set_array" "string $session" "array $tuples")
("msession_set_data" "string $session" "string $value")
("msession_timeout" "string $session" "[int $param = '']")
("msession_uniq" "int $param" "[string $classname = ''" "[string $data = '']]")
("msession_unlock" "string $session" "int $key")
("msg_get_queue" "int $key" "[int $perms = 0666]")
("msg_queue_exists" "int $key")
("msg_receive" "resource $queue" "int $desiredmsgtype" "int $msgtype" "int $maxsize" "mixed $message" "[bool $unserialize = ''" "[int $flags = ''" "[int $errorcode = '']]]")
("msg_remove_queue" "resource $queue")
("msg_send" "resource $queue" "int $msgtype" "mixed $message" "[bool $serialize = ''" "[bool $blocking = ''" "[int $errorcode = '']]]")
("msg_set_queue" "resource $queue" "array $data")
("msg_stat_queue" "resource $queue")
("msql" "")
("mt_getrandmax" "")
("mt_rand" "int $min" "int $max")
("mt_srand" "[int $seed = ''" "[int $mode = MT_RAND_MT19937]]")
("mysql_affected_rows" "[resource $link_identifier = null]")
("mysql_client_encoding" "[resource $link_identifier = null]")
("mysql_close" "[resource $link_identifier = null]")
("mysql_connect" "[string $server = ini_get(\"mysql.default_host\"")
("mysql_create_db" "string $database_name" "[resource $link_identifier = null]")
("mysql_data_seek" "resource $result" "int $row_number")
("mysql_db_name" "resource $result" "int $row" "[mixed $field = null]")
("mysql_db_query" "string $database" "string $query" "[resource $link_identifier = null]")
("mysql_drop_db" "string $database_name" "[resource $link_identifier = null]")
("mysql_errno" "[resource $link_identifier = null]")
("mysql_error" "[resource $link_identifier = null]")
("mysql_escape_string" "string $unescaped_string")
("mysql_fetch_array" "resource $result" "[int $result_type = MYSQL_BOTH]")
("mysql_fetch_assoc" "resource $result")
("mysql_fetch_field" "resource $result" "[int $field_offset = '']")
("mysql_fetch_lengths" "resource $result")
("mysql_fetch_object" "resource $result" "[string $class_name = ''" "[array $params = '']]")
("mysql_fetch_row" "resource $result")
("mysql_field_flags" "resource $result" "int $field_offset")
("mysql_field_len" "resource $result" "int $field_offset")
("mysql_field_name" "resource $result" "int $field_offset")
("mysql_field_seek" "resource $result" "int $field_offset")
("mysql_field_table" "resource $result" "int $field_offset")
("mysql_field_type" "resource $result" "int $field_offset")
("mysql_free_result" "resource $result")
("mysql_get_client_info" "")
("mysql_get_host_info" "[resource $link_identifier = null]")
("mysql_get_proto_info" "[resource $link_identifier = null]")
("mysql_get_server_info" "[resource $link_identifier = null]")
("mysql_info" "[resource $link_identifier = null]")
("mysql_insert_id" "[resource $link_identifier = null]")
("mysql_list_dbs" "[resource $link_identifier = null]")
("mysql_list_fields" "string $database_name" "string $table_name" "[resource $link_identifier = null]")
("mysql_list_processes" "[resource $link_identifier = null]")
("mysql_list_tables" "string $database" "[resource $link_identifier = null]")
("mysql_num_fields" "resource $result")
("mysql_num_rows" "resource $result")
("mysql_pconnect" "[string $server = ini_get(\"mysql.default_host\"")
("mysql_ping" "[resource $link_identifier = null]")
("mysql_query" "string $query" "[resource $link_identifier = null]")
("mysql_real_escape_string" "string $unescaped_string" "[resource $link_identifier = null]")
("mysql_result" "resource $result" "int $row" "[mixed $field = '']")
("mysql_select_db" "string $database_name" "[resource $link_identifier = null]")
("mysql_set_charset" "string $charset" "[resource $link_identifier = null]")
("mysql_stat" "[resource $link_identifier = null]")
("mysql_tablename" "resource $result" "int $i")
("mysql_thread_id" "[resource $link_identifier = null]")
("mysql_unbuffered_query" "string $query" "[resource $link_identifier = null]")
("mysqli_affected_rows" "mysqli $link")
("mysqli_autocommit" "bool $mode" "mysqli $link")
("mysqli_begin_transaction" "[int $flags = ''" "[string $name = ''" "mysqli $link]]")
("mysqli_bind_param" "")
("mysqli_bind_result" "")
("mysqli_change_user" "string $user" "string $password" "string $database" "mysqli $link")
("mysqli_character_set_name" "mysqli $link")
("mysqli_client_encoding" "")
("mysqli_close" "mysqli $link")
("mysqli_commit" "[int $flags = ''" "[string $name = ''" "mysqli $link]]")
("mysqli_connect" "")
("mysqli_connect_errno" "")
("mysqli_connect_error" "")
("mysqli_data_seek" "int $offset" "mysqli_result $result")
("mysqli_debug" "string $message")
("mysqli_disable_reads_from_master" "mysqli $link")
("mysqli_disable_rpl_parse" "mysqli $link")
("mysqli_dump_debug_info" "mysqli $link")
("mysqli_embedded_server_end" "")
("mysqli_embedded_server_start" "int $start" "array $arguments" "array $groups")
("mysqli_enable_reads_from_master" "mysqli $link")
("mysqli_enable_rpl_parse" "mysqli $link")
("mysqli_errno" "mysqli $link")
("mysqli_error" "mysqli $link")
("mysqli_error_list" "mysqli $link")
("mysqli_escape_string" "")
("mysqli_execute" "")
("mysqli_fetch" "")
("mysqli_fetch_all" "[int $resulttype = MYSQLI_NUM" "mysqli_result $result]")
("mysqli_fetch_array" "[int $resulttype = MYSQLI_BOTH" "mysqli_result $result]")
("mysqli_fetch_assoc" "mysqli_result $result")
("mysqli_fetch_field" "mysqli_result $result")
("mysqli_fetch_field_direct" "int $fieldnr" "mysqli_result $result")
("mysqli_fetch_fields" "mysqli_result $result")
("mysqli_fetch_lengths" "mysqli_result $result")
("mysqli_fetch_object" "[string $class_name = \"stdClass\"" "[array $params = ''" "mysqli_result $result]]")
("mysqli_fetch_row" "mysqli_result $result")
("mysqli_field_count" "mysqli $link")
("mysqli_field_seek" "int $fieldnr" "mysqli_result $result")
("mysqli_field_tell" "mysqli_result $result")
("mysqli_free_result" "mysqli_result $result")
("mysqli_get_cache_stats" "")
("mysqli_get_charset" "mysqli $link")
("mysqli_get_client_info" "mysqli $link")
("mysqli_get_client_stats" "")
("mysqli_get_client_version" "mysqli $link")
("mysqli_get_connection_stats" "mysqli $link")
("mysqli_get_host_info" "mysqli $link")
("mysqli_get_links_stats" "")
("mysqli_get_metadata" "")
("mysqli_get_proto_info" "mysqli $link")
("mysqli_get_server_info" "mysqli $link")
("mysqli_get_server_version" "mysqli $link")
("mysqli_get_warnings" "mysqli $link")
("mysqli_info" "mysqli $link")
("mysqli_init" "")
("mysqli_insert_id" "mysqli $link")
("mysqli_kill" "int $processid" "mysqli $link")
("mysqli_master_query" "mysqli $link" "string $query")
("mysqli_more_results" "mysqli $link")
("mysqli_multi_query" "string $query" "mysqli $link")
("mysqli_next_result" "mysqli $link")
("mysqli_num_fields" "mysqli_result $result")
("mysqli_num_rows" "mysqli_result $result")
("mysqli_options" "int $option" "mixed $value" "mysqli $link")
("mysqli_param_count" "")
("mysqli_ping" "mysqli $link")
("mysqli_poll" "array $read" "array $error" "array $reject" "int $sec" "[int $usec = '']")
("mysqli_prepare" "string $query" "mysqli $link")
("mysqli_query" "string $query" "[int $resultmode = MYSQLI_STORE_RESULT" "mysqli $link]")
("mysqli_real_connect" "[string $host = ''" "[string $username = ''" "[string $passwd = ''" "[string $dbname = ''" "[int $port = ''" "[string $socket = ''" "[int $flags = ''" "mysqli $link]]]]]]]")
("mysqli_real_escape_string" "string $escapestr" "mysqli $link")
("mysqli_real_query" "string $query" "mysqli $link")
("mysqli_reap_async_query" "mysqli $link")
("mysqli_refresh" "int $options" "resource $link")
("mysqli_release_savepoint" "string $name" "mysqli $link")
("mysqli_report" "")
("mysqli_rollback" "[int $flags = ''" "[string $name = ''" "mysqli $link]]")
("mysqli_rpl_parse_enabled" "mysqli $link")
("mysqli_rpl_probe" "mysqli $link")
("mysqli_rpl_query_type" "string $query" "mysqli $link")
("mysqli_savepoint" "string $name" "mysqli $link")
("mysqli_select_db" "string $dbname" "mysqli $link")
("mysqli_send_long_data" "")
("mysqli_send_query" "string $query" "mysqli $link")
("mysqli_set_charset" "string $charset" "mysqli $link")
("mysqli_set_local_infile_default" "mysqli $link")
("mysqli_set_local_infile_handler" "mysqli $link" "callable $read_func")
("mysqli_set_opt" "")
("mysqli_slave_query" "mysqli $link" "string $query")
("mysqli_sqlstate" "mysqli $link")
("mysqli_ssl_set" "string $key" "string $cert" "string $ca" "string $capath" "string $cipher" "mysqli $link")
("mysqli_stat" "mysqli $link")
("mysqli_stmt_affected_rows" "mysqli_stmt $stmt")
("mysqli_stmt_attr_get" "int $attr" "mysqli_stmt $stmt")
("mysqli_stmt_attr_set" "int $attr" "int $mode" "mysqli_stmt $stmt")
("mysqli_stmt_bind_param" "string $types" "mixed $var1" "[mixed $... = ''" "mysqli_stmt $stmt]")
("mysqli_stmt_bind_result" "mixed $var1" "[mixed $... = ''" "mysqli_stmt $stmt]")
("mysqli_stmt_close" "mysqli_stmt $stmt")
("mysqli_stmt_data_seek" "int $offset" "mysqli_stmt $stmt")
("mysqli_stmt_errno" "mysqli_stmt $stmt")
("mysqli_stmt_error" "mysqli_stmt $stmt")
("mysqli_stmt_error_list" "mysqli_stmt $stmt")
("mysqli_stmt_execute" "mysqli_stmt $stmt")
("mysqli_stmt_fetch" "mysqli_stmt $stmt")
("mysqli_stmt_field_count" "mysqli_stmt $stmt")
("mysqli_stmt_free_result" "mysqli_stmt $stmt")
("mysqli_stmt_get_result" "mysqli_stmt $stmt")
("mysqli_stmt_get_warnings" "mysqli_stmt $stmt")
("mysqli_stmt_init" "mysqli $link")
("mysqli_stmt_insert_id" "mysqli_stmt $stmt")
("mysqli_stmt_more_results" "mysql_stmt $stmt")
("mysqli_stmt_next_result" "mysql_stmt $stmt")
("mysqli_stmt_num_rows" "mysqli_stmt $stmt")
("mysqli_stmt_param_count" "mysqli_stmt $stmt")
("mysqli_stmt_prepare" "string $query" "mysqli_stmt $stmt")
("mysqli_stmt_reset" "mysqli_stmt $stmt")
("mysqli_stmt_result_metadata" "mysqli_stmt $stmt")
("mysqli_stmt_send_long_data" "int $param_nr" "string $data" "mysqli_stmt $stmt")
("mysqli_stmt_sqlstate" "mysqli_stmt $stmt")
("mysqli_stmt_store_result" "mysqli_stmt $stmt")
("mysqli_store_result" "[int $option = ''" "mysqli $link]")
("mysqli_thread_id" "mysqli $link")
("mysqli_thread_safe" "")
("mysqli_use_result" "mysqli $link")
("mysqli_warning_count" "mysqli $link")
("natcasesort" "array $array")
("natsort" "array $array")
("next" "array $array")
("ngettext" "string $msgid1" "string $msgid2" "int $n")
("nl2br" "string $string" "[bool $is_xhtml = '']")
("nl_langinfo" "int $item")
("normalizer_get_raw_decomposition" "string $input")
("nsapi_request_headers" "")
("nsapi_response_headers" "")
("nsapi_virtual" "string $uri")
("number_format" "float $number" "int $decimals" "string $dec_point" "string $thousands_sep")
("ob_clean" "")
("ob_end_clean" "")
("ob_end_flush" "")
("ob_flush" "")
("ob_get_clean" "")
("ob_get_contents" "")
("ob_get_flush" "")
("ob_get_length" "")
("ob_get_level" "")
("ob_get_status" "[bool $full_status = FALSE]")
("ob_gzhandler" "string $buffer" "int $mode")
("ob_iconv_handler" "string $contents" "int $status")
("ob_implicit_flush" "[int $flag = 1]")
("ob_list_handlers" "")
("ob_start" "[callable $output_callback = ''" "[int $chunk_size = ''" "[int $flags = '']]]")
("octdec" "string $octal_string")
("odbc_autocommit" "resource $connection_id" "[bool $OnOff = '']")
("odbc_binmode" "resource $result_id" "int $mode")
("odbc_close" "resource $connection_id")
("odbc_close_all" "")
("odbc_columnprivileges" "resource $connection_id" "string $qualifier" "string $owner" "string $table_name" "string $column_name")
("odbc_columns" "resource $connection_id" "[string $qualifier = ''" "[string $schema = ''" "[string $table_name = ''" "[string $column_name = '']]]]")
("odbc_commit" "resource $connection_id")
("odbc_connect" "string $dsn" "string $user" "string $password" "[int $cursor_type = '']")
("odbc_cursor" "resource $result_id")
("odbc_data_source" "resource $connection_id" "int $fetch_type")
("odbc_do" "")
("odbc_error" "[resource $connection_id = '']")
("odbc_errormsg" "[resource $connection_id = '']")
("odbc_exec" "resource $connection_id" "string $query_string" "[int $flags = '']")
("odbc_execute" "resource $result_id" "[array $parameters_array = '']")
("odbc_fetch_array" "resource $result" "[int $rownumber = '']")
("odbc_fetch_into" "resource $result_id" "array $result_array" "[int $rownumber = '']")
("odbc_fetch_object" "resource $result" "[int $rownumber = '']")
("odbc_fetch_row" "resource $result_id" "[int $row_number = 1]")
("odbc_field_len" "resource $result_id" "int $field_number")
("odbc_field_name" "resource $result_id" "int $field_number")
("odbc_field_num" "resource $result_id" "string $field_name")
("odbc_field_precision" "")
("odbc_field_scale" "resource $result_id" "int $field_number")
("odbc_field_type" "resource $result_id" "int $field_number")
("odbc_foreignkeys" "resource $connection_id" "string $pk_qualifier" "string $pk_owner" "string $pk_table" "string $fk_qualifier" "string $fk_owner" "string $fk_table")
("odbc_free_result" "resource $result_id")
("odbc_gettypeinfo" "resource $connection_id" "[int $data_type = '']")
("odbc_longreadlen" "resource $result_id" "int $length")
("odbc_next_result" "resource $result_id")
("odbc_num_fields" "resource $result_id")
("odbc_num_rows" "resource $result_id")
("odbc_pconnect" "string $dsn" "string $user" "string $password" "[int $cursor_type = '']")
("odbc_prepare" "resource $connection_id" "string $query_string")
("odbc_primarykeys" "resource $connection_id" "string $qualifier" "string $owner" "string $table")
("odbc_procedurecolumns" "resource $connection_id" "string $qualifier" "string $owner" "string $proc" "string $column")
("odbc_procedures" "resource $connection_id" "string $qualifier" "string $owner" "string $name")
("odbc_result" "resource $result_id" "mixed $field")
("odbc_result_all" "resource $result_id" "[string $format = '']")
("odbc_rollback" "resource $connection_id")
("odbc_setoption" "resource $id" "int $function" "int $option" "int $param")
("odbc_specialcolumns" "resource $connection_id" "int $type" "string $qualifier" "string $table" "int $scope" "int $nullable")
("odbc_statistics" "resource $connection_id" "string $qualifier" "string $owner" "string $table_name" "int $unique" "int $accuracy")
("odbc_tableprivileges" "resource $connection_id" "string $qualifier" "string $owner" "string $name")
("odbc_tables" "resource $connection_id" "[string $qualifier = ''" "[string $owner = ''" "[string $name = ''" "[string $types = '']]]]")
("opendir" "string $path" "[resource $context = '']")
("openlog" "string $ident" "int $option" "int $facility")
("openssl_cipher_iv_length" "string $method")
("openssl_csr_export" "mixed $csr" "string $out" "[bool $notext = '']")
("openssl_csr_export_to_file" "mixed $csr" "string $outfilename" "[bool $notext = '']")
("openssl_csr_get_public_key" "mixed $csr" "[bool $use_shortnames = '']")
("openssl_csr_get_subject" "mixed $csr" "[bool $use_shortnames = '']")
("openssl_csr_new" "array $dn" "resource $privkey" "[array $configargs = ''" "[array $extraattribs = '']]")
("openssl_csr_sign" "mixed $csr" "mixed $cacert" "mixed $priv_key" "int $days" "[array $configargs = ''" "[int $serial = '']]")
("openssl_decrypt" "string $data" "string $method" "string $key" "[int $options = ''" "[string $iv = \"\"" "[string $tag = \"\"" "[string $aad = \"\"]]]]")
("openssl_dh_compute_key" "string $pub_key" "resource $dh_key")
("openssl_digest" "string $data" "string $method" "[bool $raw_output = '']")
("openssl_encrypt" "string $data" "string $method" "string $key" "[int $options = ''" "[string $iv = \"\"" "[string $tag = null" "[string $aad = \"\"" "[int $tag_length = 16]]]]]")
("openssl_error_string" "")
("openssl_free_key" "resource $key_identifier")
("openssl_get_cert_locations" "")
("openssl_get_cipher_methods" "[bool $aliases = '']")
("openssl_get_curve_names" "")
("openssl_get_md_methods" "[bool $aliases = '']")
("openssl_get_privatekey" "")
("openssl_get_publickey" "")
("openssl_open" "string $sealed_data" "string $open_data" "string $env_key" "mixed $priv_key_id" "[string $method = \"RC4\"" "[string $iv = '']]")
("openssl_pbkdf2" "string $password" "string $salt" "int $key_length" "int $iterations" "[string $digest_algorithm = \"sha1\"]")
("openssl_pkcs12_export" "mixed $x509" "string $out" "mixed $priv_key" "string $pass" "[array $args = '']")
("openssl_pkcs12_export_to_file" "mixed $x509" "string $filename" "mixed $priv_key" "string $pass" "[array $args = '']")
("openssl_pkcs12_read" "string $pkcs12" "array $certs" "string $pass")
("openssl_pkcs7_decrypt" "string $infilename" "string $outfilename" "mixed $recipcert" "[mixed $recipkey = '']")
("openssl_pkcs7_encrypt" "string $infile" "string $outfile" "mixed $recipcerts" "array $headers" "[int $flags = ''" "[int $cipherid = OPENSSL_CIPHER_RC2_40]]")
("openssl_pkcs7_read" "string $infilename" "array $certs")
("openssl_pkcs7_sign" "string $infilename" "string $outfilename" "mixed $signcert" "mixed $privkey" "array $headers" "[int $flags = PKCS7_DETACHED" "[string $extracerts = '']]")
("openssl_pkcs7_verify" "string $filename" "int $flags" "[string $outfilename = ''" "[array $cainfo = ''" "[string $extracerts = ''" "[string $content = ''" "[string $p7bfilename = '']]]]]")
("openssl_pkey_export" "mixed $key" "string $out" "[string $passphrase = ''" "[array $configargs = '']]")
("openssl_pkey_export_to_file" "mixed $key" "string $outfilename" "[string $passphrase = ''" "[array $configargs = '']]")
("openssl_pkey_free" "resource $key")
("openssl_pkey_get_details" "resource $key")
("openssl_pkey_get_private" "mixed $key" "[string $passphrase = \"\"]")
("openssl_pkey_get_public" "mixed $certificate")
("openssl_pkey_new" "[array $configargs = '']")
("openssl_private_decrypt" "string $data" "string $decrypted" "mixed $key" "[int $padding = OPENSSL_PKCS1_PADDING]")
("openssl_private_encrypt" "string $data" "string $crypted" "mixed $key" "[int $padding = OPENSSL_PKCS1_PADDING]")
("openssl_public_decrypt" "string $data" "string $decrypted" "mixed $key" "[int $padding = OPENSSL_PKCS1_PADDING]")
("openssl_public_encrypt" "string $data" "string $crypted" "mixed $key" "[int $padding = OPENSSL_PKCS1_PADDING]")
("openssl_random_pseudo_bytes" "int $length" "[bool $crypto_strong = '']")
("openssl_seal" "string $data" "string $sealed_data" "array $env_keys" "array $pub_key_ids" "[string $method = \"RC4\"" "[string $iv = '']]")
("openssl_sign" "string $data" "string $signature" "mixed $priv_key_id" "[mixed $signature_alg = OPENSSL_ALGO_SHA1]")
("openssl_spki_export" "string $spkac")
("openssl_spki_export_challenge" "string $spkac")
("openssl_spki_new" "resource $privkey" "string $challenge" "[int $algorithm = '']")
("openssl_spki_verify" "string $spkac")
("openssl_verify" "string $data" "string $signature" "mixed $pub_key_id" "[mixed $signature_alg = OPENSSL_ALGO_SHA1]")
("openssl_x509_check_private_key" "mixed $cert" "mixed $key")
("openssl_x509_checkpurpose" "mixed $x509cert" "int $purpose" "[array $cainfo = array(")
("openssl_x509_export" "mixed $x509" "string $output" "[bool $notext = '']")
("openssl_x509_export_to_file" "mixed $x509" "string $outfilename" "[bool $notext = '']")
("openssl_x509_fingerprint" "mixed $x509" "[string $hash_algorithm = \"sha1\"" "[bool $raw_output = '']]")
("openssl_x509_free" "resource $x509cert")
("openssl_x509_parse" "mixed $x509cert" "[bool $shortnames = '']")
("openssl_x509_read" "mixed $x509certdata")
("ord" "string $string")
("output_add_rewrite_var" "string $name" "string $value")
("output_reset_rewrite_vars" "")
("pack" "string $format" "[mixed $... = '']")
("parse_ini_file" "string $filename" "[bool $process_sections = ''" "[int $scanner_mode = INI_SCANNER_NORMAL]]")
("parse_ini_string" "string $ini" "[bool $process_sections = ''" "[int $scanner_mode = INI_SCANNER_NORMAL]]")
("parse_str" "string $encoded_string" "[array $result = '']")
("parse_url" "string $url" "[int $component = -1]")
("passthru" "string $command" "[int $return_var = '']")
("password_get_info" "string $hash")
("password_hash" "string $password" "int $algo" "[array $options = '']")
("password_needs_rehash" "string $hash" "int $algo" "[array $options = '']")
("password_verify" "string $password" "string $hash")
("pathinfo" "string $path" "[int $options = PATHINFO_DIRNAME | PATHINFO_BASENAME | PATHINFO_EXTENSION | PATHINFO_FILENAME]")
("pclose" "resource $handle")
("pcntl_alarm" "int $seconds")
("pcntl_async_signals" "[bool $on = '']")
("pcntl_errno" "")
("pcntl_exec" "string $path" "[array $args = ''" "[array $envs = '']]")
("pcntl_fork" "")
("pcntl_get_last_error" "")
("pcntl_getpriority" "[int $pid = getmypid(")
("pcntl_setpriority" "int $priority" "[int $pid = getmypid(")
("pcntl_signal" "int $signo" "callable|int $handler" "[bool $restart_syscalls = '']")
("pcntl_signal_dispatch" "")
("pcntl_signal_get_handler" "int $signo")
("pcntl_sigprocmask" "int $how" "array $set" "[array $oldset = '']")
("pcntl_sigtimedwait" "array $set" "[array $siginfo = ''" "[int $seconds = ''" "[int $nanoseconds = '']]]")
("pcntl_sigwaitinfo" "array $set" "[array $siginfo = '']")
("pcntl_strerror" "int $errno")
("pcntl_wait" "int $status" "[int $options = ''" "[array $rusage = '']]")
("pcntl_waitpid" "int $pid" "int $status" "[int $options = ''" "[array $rusage = '']]")
("pcntl_wexitstatus" "int $status")
("pcntl_wifexited" "int $status")
("pcntl_wifsignaled" "int $status")
("pcntl_wifstopped" "int $status")
("pcntl_wstopsig" "int $status")
("pcntl_wtermsig" "int $status")
("pdo_drivers" "")
("pfsockopen" "string $hostname" "[int $port = -1" "[int $errno = ''" "[string $errstr = ''" "[float $timeout = ini_get(\"default_socket_timeout\"")
("php_ini_loaded_file" "")
("php_ini_scanned_files" "")
("php_sapi_name" "")
("php_strip_whitespace" "string $filename")
("php_uname" "[string $mode = \"a\"]")
("phpcredits" "[int $flag = CREDITS_ALL]")
("phpdbg_break_file" "string $file" "int $line")
("phpdbg_break_function" "string $function")
("phpdbg_break_method" "string $class" "string $method")
("phpdbg_break_next" "")
("phpdbg_clear" "")
("phpdbg_color" "int $element" "string $color")
("phpdbg_end_oplog" "[array $options = '']")
("phpdbg_exec" "[string $context = '']")
("phpdbg_get_executable" "[array $options = '']")
("phpdbg_prompt" "string $string")
("phpdbg_start_oplog" "")
("phpinfo" "[int $what = INFO_ALL]")
("phpversion" "[string $extension = '']")
("pi" "")
("png2wbmp" "string $pngname" "string $wbmpname" "int $dest_height" "int $dest_width" "int $threshold")
("popen" "string $command" "string $mode")
("pos" "")
("posix_access" "string $file" "[int $mode = POSIX_F_OK]")
("posix_ctermid" "")
("posix_errno" "")
("posix_get_last_error" "")
("posix_getcwd" "")
("posix_getegid" "")
("posix_geteuid" "")
("posix_getgid" "")
("posix_getgrgid" "int $gid")
("posix_getgrnam" "string $name")
("posix_getgroups" "")
("posix_getlogin" "")
("posix_getpgid" "int $pid")
("posix_getpgrp" "")
("posix_getpid" "")
("posix_getppid" "")
("posix_getpwnam" "string $username")
("posix_getpwuid" "int $uid")
("posix_getrlimit" "")
("posix_getsid" "int $pid")
("posix_getuid" "")
("posix_initgroups" "string $name" "int $base_group_id")
("posix_isatty" "mixed $fd")
("posix_kill" "int $pid" "int $sig")
("posix_mkfifo" "string $pathname" "int $mode")
("posix_mknod" "string $pathname" "int $mode" "[int $major = ''" "[int $minor = '']]")
("posix_setegid" "int $gid")
("posix_seteuid" "int $uid")
("posix_setgid" "int $gid")
("posix_setpgid" "int $pid" "int $pgid")
("posix_setrlimit" "int $resource" "int $softlimit" "int $hardlimit")
("posix_setsid" "")
("posix_setuid" "int $uid")
("posix_strerror" "int $errno")
("posix_times" "")
("posix_ttyname" "mixed $fd")
("posix_uname" "")
("pow" "number $base" "number $exp")
("preg_filter" "mixed $pattern" "mixed $replacement" "mixed $subject" "[int $limit = -1" "[int $count = '']]")
("preg_grep" "string $pattern" "array $input" "[int $flags = '']")
("preg_last_error" "")
("preg_match" "string $pattern" "string $subject" "[array $matches = ''" "[int $flags = ''" "[int $offset = '']]]")
("preg_match_all" "string $pattern" "string $subject" "[array $matches = ''" "[int $flags = ''" "[int $offset = '']]]")
("preg_quote" "string $str" "[string $delimiter = '']")
("preg_replace" "mixed $pattern" "mixed $replacement" "mixed $subject" "[int $limit = -1" "[int $count = '']]")
("preg_replace_callback" "mixed $pattern" "callable $callback" "mixed $subject" "[int $limit = -1" "[int $count = '']]")
("preg_replace_callback_array" "array $patterns_and_callbacks" "mixed $subject" "[int $limit = -1" "[int $count = '']]")
("preg_split" "string $pattern" "string $subject" "[int $limit = -1" "[int $flags = '']]")
("prev" "array $array")
("print" "string $arg")
("print_r" "mixed $expression" "[bool $return = '']")
("printf" "string $format" "[mixed $... = '']")
("proc_close" "resource $process")
("proc_get_status" "resource $process")
("proc_nice" "int $increment")
("proc_open" "string $cmd" "array $descriptorspec" "array $pipes" "[string $cwd = ''" "[array $env = ''" "[array $other_options = '']]]")
("proc_terminate" "resource $process" "[int $signal = 15]")
("property_exists" "mixed $class" "string $property")
("putenv" "string $setting")
("quoted_printable_decode" "string $str")
("quoted_printable_encode" "string $str")
("quotemeta" "string $str")
("rad2deg" "float $number")
("rand" "int $min" "int $max")
("random_bytes" "int $length")
("random_int" "int $min" "int $max")
("range" "mixed $start" "mixed $end" "[number $step = 1]")
("rawurldecode" "string $str")
("rawurlencode" "string $str")
("read_exif_data" "")
("readdir" "[resource $dir_handle = '']")
("readfile" "string $filename" "[bool $use_include_path = ''" "[resource $context = '']]")
("readgzfile" "string $filename" "[int $use_include_path = '']")
("readline" "[string $prompt = '']")
("readline_add_history" "string $line")
("readline_callback_handler_install" "string $prompt" "callable $callback")
("readline_callback_handler_remove" "")
("readline_callback_read_char" "")
("readline_clear_history" "")
("readline_completion_function" "callable $function")
("readline_info" "[string $varname = ''" "[string $newvalue = '']]")
("readline_list_history" "")
("readline_on_new_line" "")
("readline_read_history" "[string $filename = '']")
("readline_redisplay" "")
("readline_write_history" "[string $filename = '']")
("readlink" "string $path")
("realpath" "string $path")
("realpath_cache_get" "")
("realpath_cache_size" "")
("recode" "")
("recode_file" "string $request" "resource $input" "resource $output")
("recode_string" "string $request" "string $string")
("register_shutdown_function" "callable $callback" "[mixed $... = '']")
("register_tick_function" "callable $function" "[mixed $... = '']")
("rename" "string $oldname" "string $newname" "[resource $context = '']")
("reset" "array $array")
("restore_error_handler" "")
("restore_exception_handler" "")
("restore_include_path" "")
("rewind" "resource $handle")
("rewinddir" "[resource $dir_handle = '']")
("rmdir" "string $dirname" "[resource $context = '']")
("round" "float $val" "[int $precision = ''" "[int $mode = PHP_ROUND_HALF_UP]]")
("rsort" "array $array" "[int $sort_flags = SORT_REGULAR]")
("rtrim" "string $str" "[string $character_mask = '']")
("sapi_windows_cp_conv" "int|string $in_codepage" "int|string $out_codepage" "string $subject")
("sapi_windows_cp_get" "string $kind")
("sapi_windows_cp_is_utf8" "")
("sapi_windows_cp_set" "int $cp")
("sapi_windows_vt100_support" "resource $stream" "[bool $enable = '']")
("scandir" "string $directory" "[int $sorting_order = SCANDIR_SORT_ASCENDING" "[resource $context = '']]")
("sem_acquire" "resource $sem_identifier" "[bool $nowait = '']")
("sem_get" "int $key" "[int $max_acquire = 1" "[int $perm = 0666" "[int $auto_release = 1]]]")
("sem_release" "resource $sem_identifier")
("sem_remove" "resource $sem_identifier")
("serialize" "mixed $value")
("session_abort" "")
("session_cache_expire" "[string $new_cache_expire = '']")
("session_cache_limiter" "[string $cache_limiter = '']")
("session_commit" "")
("session_create_id" "[string $prefix = '']")
("session_decode" "string $data")
("session_destroy" "")
("session_encode" "")
("session_gc" "")
("session_get_cookie_params" "")
("session_id" "[string $id = '']")
("session_module_name" "[string $module = '']")
("session_name" "[string $name = '']")
("session_regenerate_id" "[bool $delete_old_session = '']")
("session_register_shutdown" "")
("session_reset" "")
("session_save_path" "[string $path = '']")
("session_set_cookie_params" "int $lifetime" "[string $path = ''" "[string $domain = ''" "[bool $secure = ''" "[bool $httponly = ''" "array $options]]]]")
("session_set_save_handler" "callable $open" "callable $close" "callable $read" "callable $write" "callable $destroy" "callable $gc" "[callable $create_sid = ''" "[callable $validate_sid = ''" "[callable $update_timestamp = ''" "object $sessionhandler" "[bool $register_shutdown = '']]]]")
("session_start" "[array $options = array(")
("session_status" "")
("session_unset" "")
("session_write_close" "")
("set_error_handler" "callable $error_handler" "[int $error_types = E_ALL | E_STRICT]")
("set_exception_handler" "callable $exception_handler")
("set_file_buffer" "")
("set_include_path" "string $new_include_path")
("set_time_limit" "int $seconds")
("setcookie" "string $name" "[string $value = \"\"" "[int $expires = ''" "[string $path = \"\"" "[string $domain = \"\"" "[bool $secure = ''" "[bool $httponly = ''" "[array $options = []]]]]]]]")
("setlocale" "int $category" "array $locale" "[string $... = '']")
("setrawcookie" "string $name" "[string $value = ''" "[int $expires = ''" "[string $path = ''" "[string $domain = ''" "[bool $secure = ''" "[bool $httponly = ''" "[array $options = []]]]]]]]")
("settype" "mixed $var" "string $type")
("sha1" "string $str" "[bool $raw_output = '']")
("sha1_file" "string $filename" "[bool $raw_output = '']")
("shell_exec" "string $cmd")
("shm_attach" "int $key" "[int $memsize = ''" "[int $perm = 0666]]")
("shm_detach" "resource $shm_identifier")
("shm_get_var" "resource $shm_identifier" "int $variable_key")
("shm_has_var" "resource $shm_identifier" "int $variable_key")
("shm_put_var" "resource $shm_identifier" "int $variable_key" "mixed $variable")
("shm_remove" "resource $shm_identifier")
("shm_remove_var" "resource $shm_identifier" "int $variable_key")
("shmop_close" "resource $shmid")
("shmop_delete" "resource $shmid")
("shmop_open" "int $key" "string $flags" "int $mode" "int $size")
("shmop_read" "resource $shmid" "int $start" "int $count")
("shmop_size" "resource $shmid")
("shmop_write" "resource $shmid" "string $data" "int $offset")
("show_source" "")
("shuffle" "array $array")
("similar_text" "string $first" "string $second" "[float $percent = '']")
("simplexml_import_dom" "DOMNode $node" "[string $class_name = \"SimpleXMLElement\"]")
("simplexml_load_file" "string $filename" "[string $class_name = \"SimpleXMLElement\"" "[int $options = ''" "[string $ns = \"\"" "[bool $is_prefix = '']]]]")
("simplexml_load_string" "string $data" "[string $class_name = \"SimpleXMLElement\"" "[int $options = ''" "[string $ns = \"\"" "[bool $is_prefix = '']]]]")
("sin" "float $arg")
("sinh" "float $arg")
("sizeof" "")
("sleep" "int $seconds")
("socket_accept" "resource $socket")
("socket_addrinfo_bind" "resource $addr")
("socket_addrinfo_connect" "resource $addr")
("socket_addrinfo_explain" "resource $addr")
("socket_addrinfo_lookup" "string $host" "[string $service = ''" "[array $hints = '']]")
("socket_bind" "resource $socket" "string $address" "[int $port = '']")
("socket_clear_error" "[resource $socket = '']")
("socket_close" "resource $socket")
("socket_cmsg_space" "int $level" "int $type" "[int $n = '']")
("socket_connect" "resource $socket" "string $address" "[int $port = '']")
("socket_create" "int $domain" "int $type" "int $protocol")
("socket_create_listen" "int $port" "[int $backlog = 128]")
("socket_create_pair" "int $domain" "int $type" "int $protocol" "array $fd")
("socket_export_stream" "resource $socket")
("socket_get_option" "resource $socket" "int $level" "int $optname")
("socket_get_status" "")
("socket_getopt" "")
("socket_getpeername" "resource $socket" "string $address" "[int $port = '']")
("socket_getsockname" "resource $socket" "string $addr" "[int $port = '']")
("socket_import_stream" "resource $stream")
("socket_last_error" "[resource $socket = '']")
("socket_listen" "resource $socket" "[int $backlog = '']")
("socket_read" "resource $socket" "int $length" "[int $type = PHP_BINARY_READ]")
("socket_recv" "resource $socket" "string $buf" "int $len" "int $flags")
("socket_recvfrom" "resource $socket" "string $buf" "int $len" "int $flags" "string $name" "[int $port = '']")
("socket_recvmsg" "resource $socket" "array $message" "[int $flags = '']")
("socket_select" "array $read" "array $write" "array $except" "int $tv_sec" "[int $tv_usec = '']")
("socket_send" "resource $socket" "string $buf" "int $len" "int $flags")
("socket_sendmsg" "resource $socket" "array $message" "[int $flags = '']")
("socket_sendto" "resource $socket" "string $buf" "int $len" "int $flags" "string $addr" "[int $port = '']")
("socket_set_block" "resource $socket")
("socket_set_blocking" "")
("socket_set_nonblock" "resource $socket")
("socket_set_option" "resource $socket" "int $level" "int $optname" "mixed $optval")
("socket_set_timeout" "")
("socket_setopt" "")
("socket_shutdown" "resource $socket" "[int $how = 2]")
("socket_strerror" "int $errno")
("socket_write" "resource $socket" "string $buffer" "[int $length = '']")
("socket_wsaprotocol_info_export" "resource  $socket" "int  $target_pid")
("socket_wsaprotocol_info_import" "string $info_id")
("socket_wsaprotocol_info_release" "string $info_id")
("sodium_add" "string $val" "string $addv")
("sodium_base642bin" "string $b64" "int $id" "[string $ignore = '']")
("sodium_bin2base64" "string $bin" "int $id")
("sodium_bin2hex" "string $bin")
("sodium_compare" "string $buf1" "string $buf2")
("sodium_crypto_aead_aes256gcm_decrypt" "string $ciphertext" "string $ad" "string $nonce" "string $key")
("sodium_crypto_aead_aes256gcm_encrypt" "string $msg" "string $ad" "string $nonce" "string $key")
("sodium_crypto_aead_aes256gcm_is_available" "")
("sodium_crypto_aead_aes256gcm_keygen" "")
("sodium_crypto_aead_chacha20poly1305_decrypt" "string $ciphertext" "string $ad" "string $nonce" "string $key")
("sodium_crypto_aead_chacha20poly1305_encrypt" "string $msg" "string $ad" "string $nonce" "string $key")
("sodium_crypto_aead_chacha20poly1305_ietf_decrypt" "string $ciphertext" "string $ad" "string $nonce" "string $key")
("sodium_crypto_aead_chacha20poly1305_ietf_encrypt" "string $msg" "string $ad" "string $nonce" "string $key")
("sodium_crypto_aead_chacha20poly1305_ietf_keygen" "")
("sodium_crypto_aead_chacha20poly1305_keygen" "")
("sodium_crypto_aead_xchacha20poly1305_ietf_decrypt" "string $ciphertext" "string $ad" "string $nonce" "string $key")
("sodium_crypto_aead_xchacha20poly1305_ietf_encrypt" "string $msg" "string $ad" "string $nonce" "string $key")
("sodium_crypto_aead_xchacha20poly1305_ietf_keygen" "")
("sodium_crypto_auth" "string $msg" "string $key")
("sodium_crypto_auth_keygen" "")
("sodium_crypto_auth_verify" "string $signature" "string $msg" "string $key")
("sodium_crypto_box" "string $msg" "string $nonce" "string $key")
("sodium_crypto_box_keypair" "")
("sodium_crypto_box_keypair_from_secretkey_and_publickey" "string $secret_key" "string $public_key")
("sodium_crypto_box_open" "string $ciphertext" "string $nonce" "string $key")
("sodium_crypto_box_publickey" "string $key")
("sodium_crypto_box_publickey_from_secretkey" "string $key")
("sodium_crypto_box_seal" "string $msg" "string $key")
("sodium_crypto_box_seal_open" "string $ciphertext" "string $key")
("sodium_crypto_box_secretkey" "string $key")
("sodium_crypto_box_seed_keypair" "string $key")
("sodium_crypto_generichash" "string $msg" "[string $key = ''" "[int $length = SODIUM_CRYPTO_GENERICHASH_BYTES]]")
("sodium_crypto_generichash_final" "string $state" "[int $length = SODIUM_CRYPTO_GENERICHASH_BYTES]")
("sodium_crypto_generichash_init" "[string $key = ''" "[int $length = SODIUM_CRYPTO_GENERICHASH_BYTES]]")
("sodium_crypto_generichash_keygen" "")
("sodium_crypto_generichash_update" "string $state" "string $msg")
("sodium_crypto_kdf_derive_from_key" "int $subkey_len" "int $subkey_id" "string $context" "string $key")
("sodium_crypto_kdf_keygen" "")
("sodium_crypto_kx_client_session_keys" "string $client_keypair" "string $server_key")
("sodium_crypto_kx_keypair" "")
("sodium_crypto_kx_publickey" "string $key")
("sodium_crypto_kx_secretkey" "string $key")
("sodium_crypto_kx_seed_keypair" "string $string")
("sodium_crypto_kx_server_session_keys" "string $server_keypair" "string $client_key")
("sodium_crypto_pwhash" "int $length" "string $password" "string $salt" "int $opslimit" "int $memlimit" "[int $alg = '']")
("sodium_crypto_pwhash_scryptsalsa208sha256" "int $length" "string $password" "string $salt" "int $opslimit" "int $memlimit")
("sodium_crypto_pwhash_scryptsalsa208sha256_str" "string $password" "int $opslimit" "int $memlimit")
("sodium_crypto_pwhash_scryptsalsa208sha256_str_verify" "string $hash" "string $password")
("sodium_crypto_pwhash_str" "string $password" "int $opslimit" "int $memlimit")
("sodium_crypto_pwhash_str_needs_rehash" "string $password" "int $opslimit" "int $memlimit")
("sodium_crypto_pwhash_str_verify" "string $hash" "string $password")
("sodium_crypto_scalarmult" "string $n" "string $p")
("sodium_crypto_scalarmult_base" "")
("sodium_crypto_secretbox" "string $string" "string $nonce" "string $key")
("sodium_crypto_secretbox_keygen" "")
("sodium_crypto_secretbox_open" "string $ciphertext" "string $nonce" "string $key")
("sodium_crypto_secretstream_xchacha20poly1305_init_pull" "string $header" "string $key")
("sodium_crypto_secretstream_xchacha20poly1305_init_push" "string $key")
("sodium_crypto_secretstream_xchacha20poly1305_keygen" "")
("sodium_crypto_secretstream_xchacha20poly1305_pull" "string $state" "string $c" "[string $ad = '']")
("sodium_crypto_secretstream_xchacha20poly1305_push" "string $state" "string $msg" "[string $ad = ''" "[int $tag = '']]")
("sodium_crypto_secretstream_xchacha20poly1305_rekey" "string $state")
("sodium_crypto_shorthash" "string $msg" "string $key")
("sodium_crypto_shorthash_keygen" "")
("sodium_crypto_sign" "string $msg" "string $secret_key")
("sodium_crypto_sign_detached" "string $msg" "string $secretkey")
("sodium_crypto_sign_ed25519_pk_to_curve25519" "string $key")
("sodium_crypto_sign_ed25519_sk_to_curve25519" "string $key")
("sodium_crypto_sign_keypair" "")
("sodium_crypto_sign_keypair_from_secretkey_and_publickey" "string $secret_key" "string $public_key")
("sodium_crypto_sign_open" "string $string" "string $public_key")
("sodium_crypto_sign_publickey" "string $keypair")
("sodium_crypto_sign_publickey_from_secretkey" "string $key")
("sodium_crypto_sign_secretkey" "string $key")
("sodium_crypto_sign_seed_keypair" "string $key")
("sodium_crypto_sign_verify_detached" "string $signature" "string $msg" "string $public_key")
("sodium_crypto_stream" "int $length" "string $nonce" "string $key")
("sodium_crypto_stream_keygen" "")
("sodium_crypto_stream_xor" "string $msg" "string $nonce" "string $key")
("sodium_hex2bin" "string $hex" "[string $ignore = '']")
("sodium_increment" "string $val")
("sodium_memcmp" "string $buf1" "string $buf2")
("sodium_memzero" "string $buf")
("sodium_pad" "string $unpadded" "int $length")
("sodium_unpad" "string $padded" "int $length")
("sort" "array $array" "[int $sort_flags = SORT_REGULAR]")
("soundex" "string $str")
("spl_autoload" "string $class_name" "[string $file_extensions = spl_autoload_extensions(")
("spl_autoload_call" "string $class_name")
("spl_autoload_extensions" "[string $file_extensions = '']")
("spl_autoload_functions" "")
("spl_autoload_register" "[callable $autoload_function = ''" "[bool $throw = ''" "[bool $prepend = '']]]")
("spl_autoload_unregister" "mixed $autoload_function")
("spl_classes" "")
("spl_object_hash" "object $obj")
("spl_object_id" "object $obj")
("split" "string $pattern" "string $string" "[int $limit = -1]")
("spliti" "string $pattern" "string $string" "[int $limit = -1]")
("sprintf" "string $format" "[mixed $... = '']")
("sql_regcase" "string $string")
("sqrt" "float $arg")
("srand" "[int $seed = '']")
("sscanf" "string $str" "string $format" "[mixed $... = '']")
("stat" "string $filename")
("str_getcsv" "string $input" "[string $delimiter = \"" "\"" "[string $enclosure = '\"'" "[string $escape = \"\\\"]]]")
("str_ireplace" "mixed $search" "mixed $replace" "mixed $subject" "[int $count = '']")
("str_pad" "string $input" "int $pad_length" "[string $pad_string = \" \"" "[int $pad_type = STR_PAD_RIGHT]]")
("str_repeat" "string $input" "int $multiplier")
("str_replace" "mixed $search" "mixed $replace" "mixed $subject" "[int $count = '']")
("str_rot13" "string $str")
("str_shuffle" "string $str")
("str_split" "string $string" "[int $split_length = 1]")
("str_word_count" "string $string" "[int $format = ''" "[string $charlist = '']]")
("strcasecmp" "string $str1" "string $str2")
("strchr" "")
("strcmp" "string $str1" "string $str2")
("strcoll" "string $str1" "string $str2")
("strcspn" "string $subject" "string $mask" "[int $start = ''" "[int $length = '']]")
("stream_bucket_append" "resource $brigade" "object $bucket")
("stream_bucket_make_writeable" "resource $brigade")
("stream_bucket_new" "resource $stream" "string $buffer")
("stream_bucket_prepend" "resource $brigade" "object $bucket")
("stream_context_create" "[array $options = ''" "[array $params = '']]")
("stream_context_get_default" "[array $options = '']")
("stream_context_get_options" "resource $stream_or_context")
("stream_context_get_params" "resource $stream_or_context")
("stream_context_set_default" "array $options")
("stream_context_set_option" "resource $stream_or_context" "string $wrapper" "string $option" "mixed $value" "array $options")
("stream_context_set_params" "resource $stream_or_context" "array $params")
("stream_copy_to_stream" "resource $source" "resource $dest" "[int $maxlength = -1" "[int $offset = '']]")
("stream_filter_append" "resource $stream" "string $filtername" "[int $read_write = ''" "[mixed $params = '']]")
("stream_filter_prepend" "resource $stream" "string $filtername" "[int $read_write = ''" "[mixed $params = '']]")
("stream_filter_register" "string $filtername" "string $classname")
("stream_filter_remove" "resource $stream_filter")
("stream_get_contents" "resource $handle" "[int $maxlength = -1" "[int $offset = -1]]")
("stream_get_filters" "")
("stream_get_line" "resource $handle" "int $length" "[string $ending = '']")
("stream_get_meta_data" "resource $stream")
("stream_get_transports" "")
("stream_get_wrappers" "")
("stream_is_local" "mixed $stream_or_url")
("stream_isatty" "resource $stream")
("stream_notification_callback" "int $notification_code" "int $severity" "string $message" "int $message_code" "int $bytes_transferred" "int $bytes_max")
("stream_register_wrapper" "")
("stream_resolve_include_path" "string $filename")
("stream_select" "array $read" "array $write" "array $except" "int $tv_sec" "[int $tv_usec = '']")
("stream_set_blocking" "resource $stream" "bool $mode")
("stream_set_chunk_size" "resource $fp" "int $chunk_size")
("stream_set_read_buffer" "resource $stream" "int $buffer")
("stream_set_timeout" "resource $stream" "int $seconds" "[int $microseconds = '']")
("stream_set_write_buffer" "resource $stream" "int $buffer")
("stream_socket_accept" "resource $server_socket" "[float $timeout = ini_get(\"default_socket_timeout\"")
("stream_socket_client" "string $remote_socket" "[int $errno = ''" "[string $errstr = ''" "[float $timeout = ini_get(\"default_socket_timeout\"")
("stream_socket_enable_crypto" "resource $stream" "bool $enable" "[int $crypto_type = ''" "[resource $session_stream = '']]")
("stream_socket_get_name" "resource $handle" "bool $want_peer")
("stream_socket_pair" "int $domain" "int $type" "int $protocol")
("stream_socket_recvfrom" "resource $socket" "int $length" "[int $flags = ''" "[string $address = '']]")
("stream_socket_sendto" "resource $socket" "string $data" "[int $flags = ''" "[string $address = '']]")
("stream_socket_server" "string $local_socket" "[int $errno = ''" "[string $errstr = ''" "[int $flags = STREAM_SERVER_BIND | STREAM_SERVER_LISTEN" "[resource $context = '']]]]")
("stream_socket_shutdown" "resource $stream" "int $how")
("stream_supports_lock" "resource $stream")
("stream_wrapper_register" "string $protocol" "string $classname" "[int $flags = '']")
("stream_wrapper_restore" "string $protocol")
("stream_wrapper_unregister" "string $protocol")
("strftime" "string $format" "[int $timestamp = time(")
("strip_tags" "string $str" "[string $allowable_tags = '']")
("stripcslashes" "string $str")
("stripos" "string $haystack" "mixed $needle" "[int $offset = '']")
("stripslashes" "string $str")
("stristr" "string $haystack" "mixed $needle" "[bool $before_needle = '']")
("strlen" "string $string")
("strnatcasecmp" "string $str1" "string $str2")
("strnatcmp" "string $str1" "string $str2")
("strncasecmp" "string $str1" "string $str2" "int $len")
("strncmp" "string $str1" "string $str2" "int $len")
("strpbrk" "string $haystack" "string $char_list")
("strpos" "string $haystack" "mixed $needle" "[int $offset = '']")
("strptime" "string $date" "string $format")
("strrchr" "string $haystack" "mixed $needle")
("strrev" "string $string")
("strripos" "string $haystack" "mixed $needle" "[int $offset = '']")
("strrpos" "string $haystack" "mixed $needle" "[int $offset = '']")
("strspn" "string $subject" "string $mask" "[int $start = ''" "[int $length = '']]")
("strstr" "string $haystack" "mixed $needle" "[bool $before_needle = '']")
("strtok" "string $str" "string $token")
("strtolower" "string $string")
("strtotime" "string $time" "[int $now = time(")
("strtoupper" "string $string")
("strtr" "string $str" "string $from" "string $to" "array $replace_pairs")
("strval" "mixed $var")
("substr" "string $string" "int $start" "[int $length = '']")
("substr_compare" "string $main_str" "string $str" "int $offset" "[int $length = ''" "[bool $case_insensitivity = '']]")
("substr_count" "string $haystack" "string $needle" "[int $offset = ''" "[int $length = '']]")
("substr_replace" "mixed $string" "mixed $replacement" "mixed $start" "[mixed $length = '']")
("symlink" "string $target" "string $link")
("sys_get_temp_dir" "")
("sys_getloadavg" "")
("syslog" "int $priority" "string $message")
("system" "string $command" "[int $return_var = '']")
("tan" "float $arg")
("tanh" "float $arg")
("tempnam" "string $dir" "string $prefix")
("textdomain" "string $text_domain")
("time" "")
("time_nanosleep" "int $seconds" "int $nanoseconds")
("time_sleep_until" "float $timestamp")
("timezone_abbreviations_list" "")
("timezone_identifiers_list" "")
("timezone_location_get" "")
("timezone_name_from_abbr" "string $abbr" "[int $gmtOffset = -1" "[int $isdst = -1]]")
("timezone_name_get" "")
("timezone_offset_get" "")
("timezone_open" "")
("timezone_transitions_get" "")
("timezone_version_get" "")
("tmpfile" "")
("token_get_all" "string $source" "[int $flags = '']")
("token_name" "int $token")
("touch" "string $filename" "[int $time = time(")
("trait_exists" "string $traitname" "[bool $autoload = '']")
("trigger_error" "string $error_msg" "[int $error_type = E_USER_NOTICE]")
("trim" "string $str" "[string $character_mask = \" \t\n\r\0\x0B\"]")
("uasort" "array $array" "callable $value_compare_func")
("ucfirst" "string $str")
("ucwords" "string $str" "[string $delimiters = \" \t\r\n\f\v\"]")
("uksort" "array $array" "callable $key_compare_func")
("umask" "[int $mask = '']")
("uniqid" "[string $prefix = \"\"" "[bool $more_entropy = '']]")
("unixtojd" "[int $timestamp = time(")
("unlink" "string $filename" "[resource $context = '']")
("unpack" "string $format" "string $data" "[int $offset = '']")
("unregister_tick_function" "callable $function")
("unserialize" "string $str" "[array $options = '']")
("unset" "mixed $var" "[mixed $... = '']")
("urldecode" "string $str")
("urlencode" "string $str")
("user_error" "")
("usleep" "int $micro_seconds")
("usort" "array $array" "callable $value_compare_func")
("utf8_decode" "string $data")
("utf8_encode" "string $data")
("var_dump" "mixed $expression" "[mixed $... = '']")
("var_export" "mixed $expression" "[bool $return = '']")
("version_compare" "string $version1" "string $version2" "string $operator")
("vfprintf" "resource $handle" "string $format" "array $args")
("virtual" "string $filename")
("vprintf" "string $format" "array $args")
("vsprintf" "string $format" "array $args")
("wordwrap" "string $str" "[int $width = 75" "[string $break = \"\n\"" "[bool $cut = '']]]")
("xml_error_string" "int $code")
("xml_get_current_byte_index" "resource $parser")
("xml_get_current_column_number" "resource $parser")
("xml_get_current_line_number" "resource $parser")
("xml_get_error_code" "resource $parser")
("xml_parse" "resource $parser" "string $data" "[bool $is_final = '']")
("xml_parse_into_struct" "resource $parser" "string $data" "array $values" "[array $index = '']")
("xml_parser_create" "[string $encoding = '']")
("xml_parser_create_ns" "[string $encoding = ''" "[string $separator = \":\"]]")
("xml_parser_free" "resource $parser")
("xml_parser_get_option" "resource $parser" "int $option")
("xml_parser_set_option" "resource $parser" "int $option" "mixed $value")
("xml_set_character_data_handler" "resource $parser" "callable $handler")
("xml_set_default_handler" "resource $parser" "callable $handler")
("xml_set_element_handler" "resource $parser" "callable $start_element_handler" "callable $end_element_handler")
("xml_set_end_namespace_decl_handler" "resource $parser" "callable $handler")
("xml_set_external_entity_ref_handler" "resource $parser" "callable $handler")
("xml_set_notation_decl_handler" "resource $parser" "callable $handler")
("xml_set_object" "resource $parser" "object $object")
("xml_set_processing_instruction_handler" "resource $parser" "callable $handler")
("xml_set_start_namespace_decl_handler" "resource $parser" "callable $handler")
("xml_set_unparsed_entity_decl_handler" "resource $parser" "callable $handler")
("xmlrpc_decode" "string $xml" "[string $encoding = \"iso-8859-1\"]")
("xmlrpc_decode_request" "string $xml" "string $method" "[string $encoding = '']")
("xmlrpc_encode" "mixed $value")
("xmlrpc_encode_request" "string $method" "mixed $params" "[array $output_options = '']")
("xmlrpc_get_type" "mixed $value")
("xmlrpc_is_fault" "array $arg")
("xmlrpc_parse_method_descriptions" "string $xml")
("xmlrpc_server_add_introspection_data" "resource $server" "array $desc")
("xmlrpc_server_call_method" "resource $server" "string $xml" "mixed $user_data" "[array $output_options = '']")
("xmlrpc_server_create" "")
("xmlrpc_server_destroy" "resource $server")
("xmlrpc_server_register_introspection_callback" "resource $server" "string $function")
("xmlrpc_server_register_method" "resource $server" "string $method_name" "string $function")
("xmlrpc_set_type" "string $value" "string $type")
("zend_thread_id" "")
("zend_version" "")
("zip_close" "resource $zip")
("zip_entry_close" "resource $zip_entry")
("zip_entry_compressedsize" "resource $zip_entry")
("zip_entry_compressionmethod" "resource $zip_entry")
("zip_entry_filesize" "resource $zip_entry")
("zip_entry_name" "resource $zip_entry")
("zip_entry_open" "resource $zip" "resource $zip_entry" "[string $mode = '']")
("zip_entry_read" "resource $zip_entry" "[int $length = 1024]")
("zip_open" "string $filename")
("zip_read" "resource $zip")
("zlib_decode" "string $data" "[string $max_decoded_len = '']")
("zlib_encode" "string $data" "int $encoding" "[int $level = -1]")
("zlib_get_coding_type" "")
)